=== tetherless-world/POEM/XML/81_Agents.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="_x0038_1_Agents" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="_x0038_1_Agents">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="AgentID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="GUID" type="9" value="k3p9DduqdEK+oGYI5c1kaw==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACTen0N26p0Qr6gZgjlzWRrAAAAAGOTmRlyP+ZAAAAAAAAAAAA4ADEA
XwBBAGcAZQBuAHQAcwAAAAAAAAC/hNFItTK2R4/+4yO8UhmrBwAAAJN6fQ3bqnRC
vqBmCOXNZGtBAGcAZQBuAHQASQBEAAAAAAAAANt/28ZAKcBCvNoFNr8m5fgHAAAA
k3p9DduqdEK+oGYI5c1ka0EAZwBlAG4AdABOAGEAbQBlAAAAAAAAAMY76XADQj5H
tvvTKTuebQAHAAAAk3p9DduqdEK+oGYI5c1ka0EAcwBzAG8AYwBpAGEAdABlAGQA
IABEAE8ASQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAUAAAAAAAAAAAAAAAAA
AAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="AgentID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="v4TRSLUytkeP/uMjvFIZqw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="AgentName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="23/bxkApwEK82gU2vybl+A==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="3210"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="Description" type="10" value="This is the name of the group assigned by us."/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Associated_x0020_DOI" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="3870"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="0"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="xjvpcANCPke2+9MpO55tAA==
"/>
<od:fieldProperty name="Description" type="10" value="If there is a specific doi that is the full set of group members as authors"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== tetherless-world/POEM/rcads/data/xml/81_Agents.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="81_Agents.xsd" generated="2024-10-08T11:26:44">
<_x0038_1_Agents>
<AgentID>1</AgentID>
<AgentName>Chorpita &amp; Spence</AgentName>
</_x0038_1_Agents>
<_x0038_1_Agents>
<AgentID>2</AgentID>
<AgentName>Chorpita &amp; Becker</AgentName>
</_x0038_1_Agents>
<_x0038_1_Agents>
<AgentID>3</AgentID>
<AgentName>Caplan NIH R16 Early Intervention Team</AgentName>
</_x0038_1_Agents>
<_x0038_1_Agents>
<AgentID>5</AgentID>
<AgentName>Ebesutani et al. 2012</AgentName>
<Associated_x0020_DOI>https://doi.org/10.1037/a0027283</Associated_x0020_DOI>
</_x0038_1_Agents>
<_x0038_1_Agents>
<AgentID>6</AgentID>
<AgentName>Ebesutani et al. 2010</AgentName>
<Associated_x0020_DOI>https://doi.org/10.1007/s10802-009-9363-8</Associated_x0020_DOI>
</_x0038_1_Agents>
<_x0038_1_Agents>
<AgentID>7</AgentID>
<AgentName>RCADS Team</AgentName>
</_x0038_1_Agents>
<_x0038_1_Agents>
<AgentID>8</AgentID>
<AgentName>Park et al. 2016</AgentName>
<Associated_x0020_DOI>10.1007/s10862-015-9517-7</Associated_x0020_DOI>
</_x0038_1_Agents>
</dataroot>
