=== tetherless-world/POEM/rcads/data/xml/00_InstrumentFamilies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="_x0030_0_InstrumentFamilies" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="_x0030_0_InstrumentFamilies">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="CollectionID" index-key="FamilyID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="FamilyID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="GUID" type="9" value="g9GQbTtrxkSu+81/sfvB3g==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACD0ZBtO2vGRK77zX+x+8HeAAAAAIo/nn0RYuZAAAAAAAAAAAAwADAA
XwBJAG4AcwB0AHIAdQBtAGUAbgB0AEMAbwBsAGwAZQBjAHQAaQBvAG4AcwAAAAAA
AAAqNUP9k6naSrQQc4RmoPUdAAAAAGrCRYDuVOZAAAAAAAAAAAA0ADAAXwBTAGMA
YQBsAGUAcwAAAAAAAAB+8/7JF/cqT6ikgI0Wn9NyBwAAAIPRkG07a8ZErvvNf7H7
wd5GAGEAbQBpAGwAeQBJAEQAAAAAAAAA1KmKYvfJ2EyPNGlsjyEJMAcAAACD0ZBt
O2vGRK77zX+x+8HeSQBuAHMAdAByAHUAbQBlAG4AdABGAGEAbQBpAGwAeQAAAAAA
AAAuOQ98Ply0QrbIbq8F+3K0BwAAAIPRkG07a8ZErvvNf7H7wd5JAG4AcwB0AHIA
dQBtAGUAbgB0AEYAYQBtAGkAbAB5AEYAdQBsAGwATgBhAG0AZQAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAADAAAAAUAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="FamilyID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="fvP+yRf3Kk+opICNFp/Tcg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="InstrumentFamily" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="1KmKYvfJ2EyPNGlsjyEJMA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1830"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="Description" type="10" value="A short name for instruments in a collection. A collection member must have the same or a subset of the original members&apos; item stem concepts."/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="InstrumentFamilyFullName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="LjkPfD5ctEK2yG6vBftytA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="4740"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="Description" type="10" value="The full name of the instrument collection."/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== tetherless-world/POEM/rcads/data/xml/00_InstrumentFamilies.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="00_InstrumentFamilies.xsd" generated="2025-08-28T15:29:46">
<_x0030_0_InstrumentFamilies>
<FamilyID>1</FamilyID>
<InstrumentFamily>RCADS</InstrumentFamily>
<InstrumentFamilyFullName>Revised Child Anxiety and Depression Scale</InstrumentFamilyFullName>
</_x0030_0_InstrumentFamilies>
<_x0030_0_InstrumentFamilies>
<FamilyID>2</FamilyID>
<InstrumentFamily>PSWQ-C</InstrumentFamily>
<InstrumentFamilyFullName>Penn State Worry Questionnaire for Children</InstrumentFamilyFullName>
</_x0030_0_InstrumentFamilies>
<_x0030_0_InstrumentFamilies>
<FamilyID>3</FamilyID>
<InstrumentFamily>MTT</InstrumentFamily>
<InstrumentFamilyFullName>My Thoughts About Therapy</InstrumentFamilyFullName>
</_x0030_0_InstrumentFamilies>
<_x0030_0_InstrumentFamilies>
<FamilyID>4</FamilyID>
<InstrumentFamily>PHQ</InstrumentFamily>
<InstrumentFamilyFullName>Patient Health Questionnaire</InstrumentFamilyFullName>
</_x0030_0_InstrumentFamilies>
<_x0030_0_InstrumentFamilies>
<FamilyID>5</FamilyID>
<InstrumentFamily>GAD</InstrumentFamily>
<InstrumentFamilyFullName>General Anxiety Disorder</InstrumentFamilyFullName>
</_x0030_0_InstrumentFamilies>
</dataroot>
