=== tetherless-world/POEM/rcads/data/xml/01_InstrumentEntities.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="_x0030_1_InstrumentEntities" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="_x0030_1_InstrumentEntities">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="InstrumentEntityTypeID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="GUID" type="9" value="HeoT5MsX2EKTMNZgODluiA==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAAd6hPkyxfYQpMw1mA4OW6IAAAAANA5PjX1PuZAAAAAAAAAAAAwADEA
XwBJAG4AcwB0AHIAdQBtAGUAbgB0AEUAbgB0AGkAdABpAGUAcwAAAAAAAADvdXtW
10dNRLRdgntgI8VuAAAAAEW/Ga70PuZAAAAAAAAAAAAwADMAXwBBAGMAdABpAHYA
aQB0AGkAZQBzAAAAAAAAANGtwobW1ptCi9n3qSelMsAHAAAAHeoT5MsX2EKTMNZg
ODluiEkAbgBzAHQAcgB1AG0AZQBuAHQARQBuAHQAaQB0AHkAVAB5AHAAZQBJAEQA
AAAAAAAAfdZqV0IACkem7SiwxtJutAcAAAAd6hPkyxfYQpMw1mA4OW6ISQBuAHMA
dAByAHUAbQBlAG4AdABFAG4AdABpAHQAeQBUAHkAcABlAAAAAAAAADWS2ZrujepD
lq/Z3+ncyesHAAAAHeoT5MsX2EKTMNZgODluiFQAYQBiAGwAZQBTAG8AdQByAGMA
ZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAUAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="InstrumentEntityTypeID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="0a3ChtbWm0KL2fepJ6UywA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="InstrumentEntityType" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="fdZqV0IACkem7SiwxtJutA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2445"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="TableSource" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="3735"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="NZLZmu6N6kOWr9nf6dzJ6w==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== tetherless-world/POEM/rcads/data/xml/01_InstrumentEntities.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="01_InstrumentEntities.xsd" generated="2025-08-28T15:29:56">
<_x0030_1_InstrumentEntities>
<InstrumentEntityTypeID>1</InstrumentEntityTypeID>
<InstrumentEntityType>Instrument</InstrumentEntityType>
<TableSource>10_Instruments</TableSource>
</_x0030_1_InstrumentEntities>
<_x0030_1_InstrumentEntities>
<InstrumentEntityTypeID>2</InstrumentEntityTypeID>
<InstrumentEntityType>InstrumentComponent</InstrumentEntityType>
<TableSource>11_InstrumentComponents</TableSource>
</_x0030_1_InstrumentEntities>
<_x0030_1_InstrumentEntities>
<InstrumentEntityTypeID>3</InstrumentEntityTypeID>
<InstrumentEntityType>Item</InstrumentEntityType>
<TableSource>20_Items</TableSource>
</_x0030_1_InstrumentEntities>
<_x0030_1_InstrumentEntities>
<InstrumentEntityTypeID>4</InstrumentEntityTypeID>
<InstrumentEntityType>ItemStem</InstrumentEntityType>
<TableSource>21_ItemStems</TableSource>
</_x0030_1_InstrumentEntities>
<_x0030_1_InstrumentEntities>
<InstrumentEntityTypeID>5</InstrumentEntityTypeID>
<InstrumentEntityType>ItemStemConcept</InstrumentEntityType>
<TableSource>22_ItemStemConcepts</TableSource>
</_x0030_1_InstrumentEntities>
<_x0030_1_InstrumentEntities>
<InstrumentEntityTypeID>6</InstrumentEntityTypeID>
<InstrumentEntityType>Codebook</InstrumentEntityType>
<TableSource>30_Codebooks</TableSource>
</_x0030_1_InstrumentEntities>
<_x0030_1_InstrumentEntities>
<InstrumentEntityTypeID>7</InstrumentEntityTypeID>
<InstrumentEntityType>ResponseOption</InstrumentEntityType>
<TableSource>31_ResponseOptions</TableSource>
</_x0030_1_InstrumentEntities>
<_x0030_1_InstrumentEntities>
<InstrumentEntityTypeID>8</InstrumentEntityTypeID>
<InstrumentEntityType>ResponseOptionConcept</InstrumentEntityType>
<TableSource>34_ResponseOptionConcepts</TableSource>
</_x0030_1_InstrumentEntities>
<_x0030_1_InstrumentEntities>
<InstrumentEntityTypeID>9</InstrumentEntityTypeID>
<InstrumentEntityType>Scale</InstrumentEntityType>
<TableSource>40_Scales</TableSource>
</_x0030_1_InstrumentEntities>
<_x0030_1_InstrumentEntities>
<InstrumentEntityTypeID>10</InstrumentEntityTypeID>
<InstrumentEntityType>InstrumentCollections</InstrumentEntityType>
<TableSource>00_InstrumentCollections</TableSource>
</_x0030_1_InstrumentEntities>
</dataroot>
