=== tetherless-world/POEM/rcads/data/xml/03_Activities.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="_x0030_3_Activities" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="_x0030_3_Activities">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="ActivityID" index-key="ActivityID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="GenEnityID" index-key="GenEntityID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ActivityID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:index index-name="UsedEntityID" index-key="UsedEntityID " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACY54/a8F7wRY6fFmYVqa/SAAAAAIAnowbyYeZAAAAAAAAAAAAwADMA
XwBBAGMAdABpAHYAaQB0AGkAZQBzAAAAAAAAAP3PHxGb0IhJutS2MS5FUMMHAAAA
mOeP2vBe8EWOnxZmFamv0kEAYwB0AGkAdgBpAHQAeQBJAEQAAAAAAAAA54t0Y6qn
6EqiAsESQiPT9AcAAACY54/a8F7wRY6fFmYVqa/SQQBjAHQAaQB2AGkAdAB5AE4A
YQBtAGUAAAAAAAAA+AcyJqfyHEK5e3glViJsUQAAAAB4JynslWDmQAAAAAAAAAAA
OAAxAF8AQQBnAGUAbgB0AHMAAAAAAAAARsMKon6q+0OSNvv1qelwvwcAAAD4BzIm
p/IcQrl7eCVWImxRQQBnAGUAbgB0AEkARAAAAAAAAACL0zcGDQk1T6xIoAqWWtna
BwAAAPgHMian8hxCuXt4JVYibFFBAGcAZQBuAHQATgBhAG0AZQAAAAAAAACMtvSs
97FnQLFGus6WZ8F4BwAAAJjnj9rwXvBFjp8WZhWpr9JBAHMAcwBvAGMAaQBhAHQA
ZQBkAEEAZwBlAG4AdAAAAAAAAAD3MXillNHfQITkOONbbKjABwAAAJjnj9rwXvBF
jp8WZhWpr9JBAGMAdABpAHYAaQB0AHkARABhAHQAZQAAAAAAAAAd6hPkyxfYQpMw
1mA4OW6IAAAAAFmmcz31PuZAAAAAAAAAAAAwADEAXwBJAG4AcwB0AHIAdQBtAGUA
bgB0AEUAbgB0AGkAdABpAGUAcwAAAAAAAADRrcKG1tabQovZ96knpTLABwAAAB3q
E+TLF9hCkzDWYDg5bohJAG4AcwB0AHIAdQBtAGUAbgB0AEUAbgB0AGkAdAB5AFQA
eQBwAGUASQBEAAAAAAAAAH3WaldCAApHpu0osMbSbrQHAAAAHeoT5MsX2EKTMNZg
ODluiEkAbgBzAHQAcgB1AG0AZQBuAHQARQBuAHQAaQB0AHkAVAB5AHAAZQAAAAAA
AACpo29bGMWHRLztuIA8s0DHBwAAAJjnj9rwXvBFjp8WZhWpr9JFAG4AdABpAHQA
eQBUAHkAcABlAAAAAAAAAP3AxKKPxltFmrGkC4Kl0vMAAAAAO/WqGvJh5kAAAAAA
AAAAADAANABfAEUAbgB0AGkAdAB5AEcAcgBvAHUAcABzAAAAAAAAAN9/bRiPvQZC
sazx74XeYz0HAAAA/cDEoo/GW0WasaQLgqXS80UAbgB0AGkAdAB5AE0AYQBwAHAA
aQBuAGcASQBEAAAAAAAAAI/RwFXou+tIvgBux8FAs7IHAAAA/cDEoo/GW0WasaQL
gqXS80UAbgB0AGkAdAB5AEwAaQBzAHQATgBhAG0AZQAAAAAAAAC31ObUW9OISqfb
//pJr7qDBwAAAJjnj9rwXvBFjp8WZhWpr9JVAHMAZQBkAEUAbgB0AGkAdAB5AEkA
RAAAAAAAAACwYfneQcQOR4PYPyRQkqdTBwAAAJjnj9rwXvBFjp8WZhWpr9JHAGUA
bgBFAG4AdABpAHQAeQBJAEQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAFAAAA
AAAAAAAAAAAAAAAAAAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="SubdatasheetName" type="10" value="Table.03_Activities"/>
<od:tableProperty name="LinkChildFields" type="10" value="ActivityID"/>
<od:tableProperty name="LinkMasterFields" type="10" value="ActivityID"/>
<od:tableProperty name="GUID" type="9" value="mOeP2vBe8EWOnxZmFamv0g==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ActivityID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="/c8fEZvQiEm61LYxLkVQww==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ActivityName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="8360"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="Human readable descripitive field"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="54t0Y6qn6EqiAsESQiPT9A==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="AssociatedAgent" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="4180"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="Agent (group of people or actors) who is associated with the activity; group can be a single actor"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [81_Agents].[AgentID], [81_Agents].[AgentName] FROM 81_Agents ORDER BY [AgentName]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="jLb0rPexZ0CxRrrOlmfBeA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ActivityDate" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1560"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="Date that 1 new entity was generated from 0 or more existing entities"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowDatePicker" type="3" value="1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="9zF4pZTR30CE5DjjW2yowA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="EntityType" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1785"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="What type of entity was produced?"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [01_InstrumentEntities].[InstrumentEntityTypeID], [01_InstrumentEntities].[InstrumentEntityType] FROM 01_InstrumentEntities ORDER BY [InstrumentEntityTypeID]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="qaNvWxjFh0S87biAPLNAxw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="UsedEntityID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="4720"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="What is the ID of the entity used? (this ID can represent a list of instruments)"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="TextAlign" type="2" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [04_EntityGroups].[EntityMappingID], [04_EntityGroups].[EntityListName] FROM 04_EntityGroups ORDER BY [EntityListName]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="t9Tm1FvTiEqn2//6Sa+6gw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="GenEntityID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="3310"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="What is the ID of the entity produced? (also represents a &quot;list&quot; of elements, but can only have one item in list)"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="TextAlign" type="2" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [04_EntityGroups].[EntityMappingID], [04_EntityGroups].[EntityListName] FROM 04_EntityGroups ORDER BY [EntityListName]; "/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="sGH53kHEDkeD2D8kUJKnUw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== tetherless-world/POEM/rcads/data/xml/03_Activities.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="03_Activities.xsd" generated="2025-05-15T17:27:42">
<_x0030_3_Activities>
<ActivityID>46</ActivityID>
<ActivityName>Generated the RCADS-47-Y-JA-1 from RCADS-47-Y-EN</ActivityName>
<AssociatedAgent>29</AssociatedAgent>
<ActivityDate>2020-12-15T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>1</UsedEntityID>
<GenEntityID>54</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>47</ActivityID>
<ActivityName>Generated the RCADS-47-CG-JA-1 from RCADS-47-CG-EN</ActivityName>
<AssociatedAgent>30</AssociatedAgent>
<ActivityDate>2020-12-15T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>2</UsedEntityID>
<GenEntityID>55</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>48</ActivityID>
<ActivityName>Generated the RCADS-47-Y-JA-2 from RCADS-47-Y-JA-1 and RCADS-47-Y-EN</ActivityName>
<AssociatedAgent>29</AssociatedAgent>
<ActivityDate>2022-02-09T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>58</UsedEntityID>
<GenEntityID>60</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>49</ActivityID>
<ActivityName>Generated the RCADS-47-CG-JA-2 from RCADS-47-CG-JA-1 and RCADS-47-CG-EN</ActivityName>
<AssociatedAgent>30</AssociatedAgent>
<ActivityDate>2022-02-09T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>59</UsedEntityID>
<GenEntityID>61</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>50</ActivityID>
<ActivityName>Generated the RCADS-25-Y-JA from RCADS-47-Y-JA-2 and RCADS-25-Y-EN</ActivityName>
<AssociatedAgent>29</AssociatedAgent>
<ActivityDate>2024-03-31T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>62</UsedEntityID>
<GenEntityID>57</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>51</ActivityID>
<ActivityName>Generated the RCADS-25-CG-JA from RCADS-47-CG-JA-2 and RCADS-25-CG-EN</ActivityName>
<AssociatedAgent>30</AssociatedAgent>
<ActivityDate>2024-03-31T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>63</UsedEntityID>
<GenEntityID>56</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>52</ActivityID>
<ActivityName>Generated the RCADS-47-Y-SL from RCADS-47-Y-EN</ActivityName>
<AssociatedAgent>31</AssociatedAgent>
<ActivityDate>2015-08-19T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>1</UsedEntityID>
<GenEntityID>64</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>53</ActivityID>
<ActivityName>Generated the RCADS-47-CG-SL from RCADS-47-CG-EN</ActivityName>
<AssociatedAgent>31</AssociatedAgent>
<ActivityDate>2015-08-19T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>2</UsedEntityID>
<GenEntityID>65</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>54</ActivityID>
<ActivityName>Generated the RCADS-47-Y-FI from RCADS-47-Y-EN</ActivityName>
<AssociatedAgent>32</AssociatedAgent>
<ActivityDate>2017-08-23T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>1</UsedEntityID>
<GenEntityID>66</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>55</ActivityID>
<ActivityName>Generated the RCADS-47-CG-FI from RCADS-47-CG-EN</ActivityName>
<AssociatedAgent>32</AssociatedAgent>
<ActivityDate>2017-08-23T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>2</UsedEntityID>
<GenEntityID>67</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>56</ActivityID>
<ActivityName>Generated the RCADS-47-CG-ZH-HANS from RCADS-47-CG-EN</ActivityName>
<AssociatedAgent>33</AssociatedAgent>
<ActivityDate>2018-03-28T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>2</UsedEntityID>
<GenEntityID>70</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>57</ActivityID>
<ActivityName>Generated the RCADS-25-CG-ZH-HANS from RCADS-47-CG-ZH-HANS and RCADS-25-CG-EN</ActivityName>
<AssociatedAgent>33</AssociatedAgent>
<ActivityDate>2024-04-04T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>71</UsedEntityID>
<GenEntityID>72</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>58</ActivityID>
<ActivityName>Generated the RCADS-25-Y-ZH-HANS from RCADS-47-Y-ZH-HANS-1 and RCADS-25-Y-EN (made edits to translation from 47-item youth translated version)</ActivityName>
<AssociatedAgent>33</AssociatedAgent>
<ActivityDate>2024-03-01T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>68</UsedEntityID>
<GenEntityID>69</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>59</ActivityID>
<ActivityName>Generated the RCADS-47-Y-PL from RCADS-47-Y-EN</ActivityName>
<AssociatedAgent>34</AssociatedAgent>
<ActivityDate>2017-06-09T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>1</UsedEntityID>
<GenEntityID>78</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>60</ActivityID>
<ActivityName>Generated the RCADS-47-CG-PL from RCADS-47-CG-PL</ActivityName>
<AssociatedAgent>34</AssociatedAgent>
<ActivityDate>2017-06-09T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>2</UsedEntityID>
<GenEntityID>79</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>61</ActivityID>
<ActivityName>Generated the RCADS-25-Y-PL from RCADS-47-Y-PL and RCADS-25-Y-EN</ActivityName>
<AssociatedAgent>34</AssociatedAgent>
<ActivityDate>2017-06-09T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>82</UsedEntityID>
<GenEntityID>80</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>62</ActivityID>
<ActivityName>Generated the RCADS-25-CG-PL from RCADS-47-CG-PL and RCADS-25-CG-EN</ActivityName>
<AssociatedAgent>34</AssociatedAgent>
<ActivityDate>2017-06-09T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>83</UsedEntityID>
<GenEntityID>81</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>63</ActivityID>
<ActivityName>Generated the MTT-35-Y-NO from MTT-35-Y-EN-2</ActivityName>
<AssociatedAgent>35</AssociatedAgent>
<ActivityDate>2025-05-13T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>14</UsedEntityID>
<GenEntityID>84</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>64</ActivityID>
<ActivityName>Generated the MTT-35-CG-NO from MTT-35-CG-EN-2</ActivityName>
<AssociatedAgent>35</AssociatedAgent>
<ActivityDate>2025-05-13T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>10</UsedEntityID>
<GenEntityID>85</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>1</ActivityID>
<ActivityName>Created the RCADS-47-Y-EN</ActivityName>
<AssociatedAgent>1</AssociatedAgent>
<ActivityDate>1999-05-26T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<GenEntityID>1</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>2</ActivityID>
<ActivityName>Generated the RCADS-47-CG-EN using RCADS-47-Y-EN</ActivityName>
<AssociatedAgent>6</AssociatedAgent>
<ActivityDate>2010-02-01T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>1</UsedEntityID>
<GenEntityID>2</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>3</ActivityID>
<ActivityName>Generated the RCADS-25-Y-EN using RCADS-47-Y-EN</ActivityName>
<AssociatedAgent>5</AssociatedAgent>
<ActivityDate>2012-02-13T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>1</UsedEntityID>
<GenEntityID>3</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>4</ActivityID>
<ActivityName>Generated the RCADS-47-Y-ES using RCADS-47-Y-EN</ActivityName>
<AssociatedAgent>19</AssociatedAgent>
<EntityType>1</EntityType>
<UsedEntityID>1</UsedEntityID>
<GenEntityID>4</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>5</ActivityID>
<ActivityName>Generated MTT-35-CG-EN-3 (provider) using MTT-35-CG-EN-1</ActivityName>
<AssociatedAgent>3</AssociatedAgent>
<ActivityDate>2024-07-11T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>5</UsedEntityID>
<GenEntityID>6</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>6</ActivityID>
<ActivityName>Generated RCADS-25-Y-DE from RCADS-47-Y-DE (items) and RCADS-25-Y-EN (order)</ActivityName>
<AssociatedAgent>7</AssociatedAgent>
<ActivityDate>2024-09-01T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>9</UsedEntityID>
<GenEntityID>7</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>7</ActivityID>
<ActivityName>Generated MTT-35-CG-EN-2 (counselor) using MTT-35-CG-EN-1</ActivityName>
<AssociatedAgent>2</AssociatedAgent>
<ActivityDate>2017-12-01T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>5</UsedEntityID>
<GenEntityID>10</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>8</ActivityID>
<ActivityName>Test to compare anything to anything</ActivityName>
<AssociatedAgent>2</AssociatedAgent>
<ActivityDate>1967-02-25T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>3</UsedEntityID>
<GenEntityID>12</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>9</ActivityID>
<ActivityName>Created the MTT-35-Y-EN-1</ActivityName>
<AssociatedAgent>2</AssociatedAgent>
<ActivityDate>2017-08-14T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<GenEntityID>13</GenEntityID>
</_x0030_3_Activities>
<_x0030_3_Activities>
<ActivityID>10</ActivityID>
<ActivityName>Created the MTT-35-CG-EN-1</ActivityName>
<AssociatedAgent>2</AssociatedAgent>
<ActivityDate>2017-08-14T00:00:00</ActivityDate>
<EntityType>1</EntityType>
<UsedEntityID>13</UsedEntityID>
<GenEntityID>5</GenEntityID>
