=== tetherless-world/POEM/rcads/data/xml/03m_ActivityMethods.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="_x0030_3m_ActivityMethods" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="_x0030_3m_ActivityMethods">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="ActivityID" index-key="ActivityID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="MethodID" index-key="MethodID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAA5QBA9TECDQY/6cZckqAg0AAAAACnVF//xYeZAAAAAAAAAAAAwADMA
bQBfAEEAYwB0AGkAdgBpAHQAeQBNAGUAdABoAG8AZABzAAAAAAAAAGT8a0eAIodH
rTaqrs7TNcQHAAAAOUAQPUxAg0GP+nGXJKgINEkARAAAAAAAAAAn7ves1+dyQI9y
CUI7m3BUAAAAAMOmu3iVYOZAAAAAAAAAAAAwADMAXwBBAGMAdABpAHYAaQB0AGkA
ZQBzAAAAAAAAAISbmglTnvdIqwBN3EyFs90HAAAAJ+73rNfnckCPcglCO5twVEEA
YwB0AGkAdgBpAHQAeQBJAEQAAAAAAAAAdMBlQqlu2E6imZBuQgm3hQcAAAAn7ves
1+dyQI9yCUI7m3BUQQBjAHQAaQB2AGkAdAB5AE4AYQBtAGUAAAAAAAAAueUKyCSG
UEanLQ3L+DGPxAcAAAA5QBA9TECDQY/6cZckqAg0QQBjAHQAaQB2AGkAdAB5AEkA
RAAAAAAAAABWrFudDhlTQ55rJWXl6jV0AAAAAIt5Q1cRU+ZAAAAAAAAAAAA5ADMA
XwBNAGUAdABoAG8AZABUAHkAcABlAHMAAAAAAAAATm/q1NN7xkyqUmuRXO4WIgcA
AABWrFudDhlTQ55rJWXl6jV0TQBlAHQAaABvAGQAVAB5AHAAZQBJAEQAAAAAAAAA
F7wBFMjdIkS9Yb/45tu7uwcAAABWrFudDhlTQ55rJWXl6jV0TQBlAHQAaABvAGQA
TgBhAG0AZQAAAAAAAAARwdMwwpXKS7vHoB5rWNyoBwAAADlAED1MQINBj/pxlySo
CDRNAGUAdABoAG8AZABJAEQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAFAAAA
AAAAAAAAAAAAAAAAAAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="GUID" type="9" value="OUAQPUxAg0GP+nGXJKgINA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="Description" type="10" value="This table links provenance activties to specific methods. Activities can have 0...x methods."/>
<od:fieldProperty name="GUID" type="9" value="ZPxrR4Aih0etNqquztM1xA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ActivityID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="8060"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="Lookup for Activity table"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [03_Activities].[ActivityID], [03_Activities].[ActivityName] FROM 03_Activities ORDER BY [ActivityName]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;4350"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="4350twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="ueUKyCSGUEanLQ3L+DGPxA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="MethodID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="6170"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="Lookup for MethodType table"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [93_MethodTypes].[MethodTypeID], [93_MethodTypes].[MethodName] FROM 93_MethodTypes ORDER BY [MethodName]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;2940"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="2940twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="EcHTMMKVyku7x6Aea1jcqA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== tetherless-world/POEM/rcads/data/xml/03m_ActivityMethods.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="03m_ActivityMethods.xsd" generated="2025-09-22T19:00:41">
<_x0030_3m_ActivityMethods>
<ID>1</ID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>3</ID>
<ActivityID>18</ActivityID>
<MethodID>1</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>4</ID>
<ActivityID>18</ActivityID>
<MethodID>2</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>5</ID>
<ActivityID>18</ActivityID>
<MethodID>3</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>6</ID>
<ActivityID>19</ActivityID>
<MethodID>1</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>7</ID>
<ActivityID>19</ActivityID>
<MethodID>2</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>8</ID>
<ActivityID>19</ActivityID>
<MethodID>5</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>9</ID>
<ActivityID>21</ActivityID>
<MethodID>1</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>10</ID>
<ActivityID>21</ActivityID>
<MethodID>2</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>11</ID>
<ActivityID>21</ActivityID>
<MethodID>3</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>12</ID>
<ActivityID>21</ActivityID>
<MethodID>5</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>13</ID>
<ActivityID>21</ActivityID>
<MethodID>6</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>14</ID>
<ActivityID>22</ActivityID>
<MethodID>5</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>15</ID>
<ActivityID>22</ActivityID>
<MethodID>1</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>16</ID>
<ActivityID>18</ActivityID>
<MethodID>5</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>17</ID>
<ActivityID>24</ActivityID>
<MethodID>1</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>18</ID>
<ActivityID>27</ActivityID>
<MethodID>1</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>19</ID>
<ActivityID>27</ActivityID>
<MethodID>2</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>20</ID>
<ActivityID>27</ActivityID>
<MethodID>3</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>21</ID>
<ActivityID>27</ActivityID>
<MethodID>5</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>22</ID>
<ActivityID>4</ActivityID>
<MethodID>2</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>23</ID>
<ActivityID>4</ActivityID>
<MethodID>1</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>24</ID>
<ActivityID>4</ActivityID>
<MethodID>3</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>25</ID>
<ActivityID>4</ActivityID>
<MethodID>5</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>26</ID>
<ActivityID>31</ActivityID>
<MethodID>1</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>27</ID>
<ActivityID>33</ActivityID>
<MethodID>1</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>28</ID>
<ActivityID>33</ActivityID>
<MethodID>2</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>29</ID>
<ActivityID>33</ActivityID>
<MethodID>3</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>30</ID>
<ActivityID>33</ActivityID>
<MethodID>4</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>31</ID>
<ActivityID>33</ActivityID>
<MethodID>5</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>32</ID>
<ActivityID>33</ActivityID>
<MethodID>6</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>33</ID>
<ActivityID>34</ActivityID>
<MethodID>1</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>34</ID>
<ActivityID>34</ActivityID>
<MethodID>2</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>35</ID>
<ActivityID>34</ActivityID>
<MethodID>3</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>36</ID>
<ActivityID>34</ActivityID>
<MethodID>5</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>37</ID>
<ActivityID>34</ActivityID>
<MethodID>6</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>38</ID>
<ActivityID>34</ActivityID>
<MethodID>4</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>39</ID>
<ActivityID>32</ActivityID>
<MethodID>2</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>40</ID>
<ActivityID>32</ActivityID>
<MethodID>4</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>41</ID>
<ActivityID>32</ActivityID>
<MethodID>1</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>42</ID>
<ActivityID>32</ActivityID>
<MethodID>3</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>43</ID>
<ActivityID>35</ActivityID>
<MethodID>1</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>44</ID>
<ActivityID>16</ActivityID>
<MethodID>2</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>45</ID>
<ActivityID>16</ActivityID>
<MethodID>4</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>46</ID>
<ActivityID>16</ActivityID>
<MethodID>1</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>47</ID>
<ActivityID>16</ActivityID>
<MethodID>3</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>48</ID>
<ActivityID>35</ActivityID>
<MethodID>2</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>49</ID>
<ActivityID>35</ActivityID>
<MethodID>3</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>50</ID>
<ActivityID>37</ActivityID>
<MethodID>1</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>51</ID>
<ActivityID>37</ActivityID>
<MethodID>2</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>52</ID>
<ActivityID>37</ActivityID>
<MethodID>3</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>53</ID>
<ActivityID>37</ActivityID>
<MethodID>5</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>54</ID>
<ActivityID>36</ActivityID>
<MethodID>1</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>55</ID>
<ActivityID>36</ActivityID>
<MethodID>2</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>56</ID>
<ActivityID>36</ActivityID>
<MethodID>3</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>57</ID>
<ActivityID>36</ActivityID>
<MethodID>5</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>58</ID>
<ActivityID>38</ActivityID>
<MethodID>1</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>59</ID>
<ActivityID>38</ActivityID>
<MethodID>2</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>60</ID>
<ActivityID>38</ActivityID>
<MethodID>3</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>61</ID>
<ActivityID>38</ActivityID>
<MethodID>5</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>62</ID>
<ActivityID>38</ActivityID>
<MethodID>4</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>63</ID>
<ActivityID>41</ActivityID>
<MethodID>1</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>64</ID>
<ActivityID>41</ActivityID>
<MethodID>2</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>65</ID>
<ActivityID>41</ActivityID>
<MethodID>5</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>66</ID>
<ActivityID>40</ActivityID>
<MethodID>1</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>67</ID>
<ActivityID>40</ActivityID>
<MethodID>2</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>68</ID>
<ActivityID>40</ActivityID>
<MethodID>5</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>69</ID>
<ActivityID>45</ActivityID>
<MethodID>1</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>70</ID>
<ActivityID>45</ActivityID>
<MethodID>2</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>71</ID>
<ActivityID>45</ActivityID>
<MethodID>3</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>72</ID>
<ActivityID>45</ActivityID>
<MethodID>6</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>73</ID>
<ActivityID>45</ActivityID>
<MethodID>5</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>74</ID>
<ActivityID>44</ActivityID>
<MethodID>1</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>75</ID>
<ActivityID>44</ActivityID>
<MethodID>2</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>76</ID>
<ActivityID>44</ActivityID>
<MethodID>3</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>77</ID>
<ActivityID>44</ActivityID>
<MethodID>6</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>78</ID>
<ActivityID>44</ActivityID>
<MethodID>5</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>79</ID>
<ActivityID>47</ActivityID>
<MethodID>1</MethodID>
</_x0030_3m_ActivityMethods>
<_x0030_3m_ActivityMethods>
<ID>80</ID>
<ActivityID>47</ActivityID>
