=== tetherless-world/POEM/rcads/data/xml/03p_ActivityPersonRoles.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="_x0030_3p_ActivityPersonRoles" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="_x0030_3p_ActivityPersonRoles">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="03p_ActivityPersonRolesRoleID" index-key="RoleID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="ActivityID" index-key="ActivityID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PersonID" index-key="PersonID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAChiJB/gavdS5s15vMJiK2rAAAAAKE9mPHyYeZAAAAAAAAAAAAwADMA
cABfAEEAYwB0AGkAdgBpAHQAeQBQAGUAcgBzAG8AbgBSAG8AbABlAHMAAAAAAAAA
z2pEGGux0EerT2q6mhHoHwcAAAChiJB/gavdS5s15vMJiK2rSQBEAAAAAAAAAJjn
j9rwXvBFjp8WZhWpr9IAAAAAgCejBvJh5kAAAAAAAAAAADAAMwBfAEEAYwB0AGkA
dgBpAHQAaQBlAHMAAAAAAAAA/c8fEZvQiEm61LYxLkVQwwcAAACY54/a8F7wRY6f
FmYVqa/SQQBjAHQAaQB2AGkAdAB5AEkARAAAAAAAAADni3RjqqfoSqICwRJCI9P0
BwAAAJjnj9rwXvBFjp8WZhWpr9JBAGMAdABpAHYAaQB0AHkATgBhAG0AZQAAAAAA
AABUUyz1RJTITYftNxLV7VbPBwAAAKGIkH+Bq91LmzXm8wmIratBAGMAdABpAHYA
aQB0AHkASQBEAAAAAAAAANeE20v4gIdPlKWn6nh03qIAAAAA3hr/6JVg5kAAAAAA
AAAAADgAMABfAFAAZQByAHMAbwBuAHMAAAAAAAAA7JubWekjAUeCInoxfpJ8dwcA
AADXhNtL+ICHT5Slp+p4dN6iUABlAHIAcwBvAG4ASQBEAAAAAAAAACY14tl8Rl5C
tpDW4GR0wg8HAAAA14TbS/iAh0+UpafqeHTeolAAZQByAHMAbwBuAE4AYQBtAGUA
AAAAAAAAjq0nTYHj0UyneeaXqUqX/AcAAAChiJB/gavdS5s15vMJiK2rUABlAHIA
cwBvAG4ASQBEAAAAAAAAADkv7Y7sWOhCoS3DW+FW7/MAAAAA1gr7PRFT5kAAAAAA
AAAAADkANABfAFIAbwBsAGUAVAB5AHAAZQBzAAAAAAAAABj9IxPacD5Dka2W/o/3
hpwHAAAAOS/tjuxY6EKhLcNb4Vbv81IAbwBsAGUASQBEAAAAAAAAALbAInPbOo1A
g4bcwdAPQa8HAAAAOS/tjuxY6EKhLcNb4Vbv81IAbwBsAGUATgBhAG0AZQAAAAAA
AADyEeA1sPYkTLm3w38Sk8OiBwAAAKGIkH+Bq91LmzXm8wmIratSAG8AbABlAEkA
RAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAUAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="GUID" type="9" value="oYiQf4Gr3UubNebzCYitqw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="Description" type="10" value="This table maps people in specific roles to provenance activities. People with no roles are not listed. Known roles are listed, even when people could not be identified."/>
<od:fieldProperty name="GUID" type="9" value="z2pEGGux0EerT2q6mhHoHw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ActivityID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="5990"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="Lookup for Activity table"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [03_Activities].[ActivityID], [03_Activities].[ActivityName] FROM 03_Activities ORDER BY [ActivityName]; "/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="8640twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="VFMs9USUyE2H7TcS1e1Wzw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="PersonID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2640"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="Lookup for Person table"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [80_Persons].[PersonID], [80_Persons].[PersonName] FROM 80_Persons ORDER BY [PersonName]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="jq0nTYHj0UyneeaXqUqX/A==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="RoleID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="4050"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="Lookup for RoleType table"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [94_RoleTypes].[RoleID], [94_RoleTypes].[RoleName] FROM 94_RoleTypes ORDER BY [RoleName]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="5760twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="8hHgNbD2JEy5t8N/EpPDog==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== tetherless-world/POEM/rcads/data/xml/03p_ActivityPersonRoles.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="03p_ActivityPersonRoles.xsd" generated="2025-09-22T19:00:55">
<_x0030_3p_ActivityPersonRoles>
<ID>6</ID>
<ActivityID>19</ActivityID>
<PersonID>24</PersonID>
<RoleID>3</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>7</ID>
<ActivityID>19</ActivityID>
<PersonID>25</PersonID>
<RoleID>3</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>8</ID>
<ActivityID>53</ActivityID>
<PersonID>70</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>9</ID>
<ActivityID>22</ActivityID>
<PersonID>15</PersonID>
<RoleID>3</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>10</ID>
<ActivityID>22</ActivityID>
<PersonID>15</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>11</ID>
<ActivityID>18</ActivityID>
<PersonID>23</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>12</ID>
<ActivityID>18</ActivityID>
<PersonID>22</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>13</ID>
<ActivityID>27</ActivityID>
<PersonID>18</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>14</ID>
<ActivityID>27</ActivityID>
<PersonID>18</PersonID>
<RoleID>3</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>15</ID>
<ActivityID>27</ActivityID>
<PersonID>18</PersonID>
<RoleID>2</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>16</ID>
<ActivityID>27</ActivityID>
<PersonID>17</PersonID>
<RoleID>3</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>17</ID>
<ActivityID>27</ActivityID>
<PersonID>17</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>18</ID>
<ActivityID>27</ActivityID>
<PersonID>17</PersonID>
<RoleID>2</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>19</ID>
<ActivityID>4</ActivityID>
<PersonID>18</PersonID>
<RoleID>3</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>20</ID>
<ActivityID>4</ActivityID>
<PersonID>18</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>21</ID>
<ActivityID>4</ActivityID>
<PersonID>18</PersonID>
<RoleID>2</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>22</ID>
<ActivityID>4</ActivityID>
<PersonID>17</PersonID>
<RoleID>3</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>23</ID>
<ActivityID>4</ActivityID>
<PersonID>17</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>24</ID>
<ActivityID>4</ActivityID>
<PersonID>17</PersonID>
<RoleID>2</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>25</ID>
<ActivityID>21</ActivityID>
<PersonID>41</PersonID>
<RoleID>3</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>26</ID>
<ActivityID>21</ActivityID>
<PersonID>41</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>27</ID>
<ActivityID>21</ActivityID>
<PersonID>40</PersonID>
<RoleID>3</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>28</ID>
<ActivityID>21</ActivityID>
<PersonID>40</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>29</ID>
<ActivityID>31</ActivityID>
<PersonID>44</PersonID>
<RoleID>3</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>30</ID>
<ActivityID>33</ActivityID>
<PersonID>49</PersonID>
<RoleID>3</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>31</ID>
<ActivityID>33</ActivityID>
<PersonID>49</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>32</ID>
<ActivityID>33</ActivityID>
<PersonID>49</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>33</ID>
<ActivityID>34</ActivityID>
<PersonID>49</PersonID>
<RoleID>3</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>34</ID>
<ActivityID>34</ActivityID>
<PersonID>49</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>35</ID>
<ActivityID>34</ActivityID>
<PersonID>49</PersonID>
<RoleID>2</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>36</ID>
<ActivityID>32</ActivityID>
<PersonID>21</PersonID>
<RoleID>3</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>37</ID>
<ActivityID>32</ActivityID>
<PersonID>21</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>38</ID>
<ActivityID>32</ActivityID>
<PersonID>21</PersonID>
<RoleID>2</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>39</ID>
<ActivityID>32</ActivityID>
<PersonID>51</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>40</ID>
<ActivityID>32</ActivityID>
<PersonID>52</PersonID>
<RoleID>3</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>41</ID>
<ActivityID>32</ActivityID>
<PersonID>52</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>42</ID>
<ActivityID>32</ActivityID>
<PersonID>52</PersonID>
<RoleID>2</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>43</ID>
<ActivityID>16</ActivityID>
<PersonID>21</PersonID>
<RoleID>3</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>44</ID>
<ActivityID>16</ActivityID>
<PersonID>21</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>45</ID>
<ActivityID>16</ActivityID>
<PersonID>21</PersonID>
<RoleID>2</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>46</ID>
<ActivityID>16</ActivityID>
<PersonID>51</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>47</ID>
<ActivityID>16</ActivityID>
<PersonID>52</PersonID>
<RoleID>3</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>48</ID>
<ActivityID>16</ActivityID>
<PersonID>52</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>49</ID>
<ActivityID>16</ActivityID>
<PersonID>52</PersonID>
<RoleID>2</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>50</ID>
<ActivityID>35</ActivityID>
<PersonID>53</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>51</ID>
<ActivityID>35</ActivityID>
<PersonID>54</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>52</ID>
<ActivityID>36</ActivityID>
<PersonID>55</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>53</ID>
<ActivityID>37</ActivityID>
<PersonID>55</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>54</ID>
<ActivityID>38</ActivityID>
<PersonID>56</PersonID>
<RoleID>3</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>55</ID>
<ActivityID>38</ActivityID>
<PersonID>56</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>56</ID>
<ActivityID>38</ActivityID>
<PersonID>56</PersonID>
<RoleID>2</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>57</ID>
<ActivityID>38</ActivityID>
<PersonID>57</PersonID>
<RoleID>3</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>58</ID>
<ActivityID>38</ActivityID>
<PersonID>57</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>59</ID>
<ActivityID>38</ActivityID>
<PersonID>57</PersonID>
<RoleID>2</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>60</ID>
<ActivityID>38</ActivityID>
<PersonID>58</PersonID>
<RoleID>3</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>61</ID>
<ActivityID>38</ActivityID>
<PersonID>58</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>62</ID>
<ActivityID>38</ActivityID>
<PersonID>58</PersonID>
<RoleID>2</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>63</ID>
<ActivityID>38</ActivityID>
<PersonID>59</PersonID>
<RoleID>3</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>64</ID>
<ActivityID>38</ActivityID>
<PersonID>59</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>65</ID>
<ActivityID>38</ActivityID>
<PersonID>59</PersonID>
<RoleID>2</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>66</ID>
<ActivityID>41</ActivityID>
<PersonID>60</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>67</ID>
<ActivityID>41</ActivityID>
<PersonID>61</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>68</ID>
<ActivityID>40</ActivityID>
<PersonID>60</PersonID>
<RoleID>1</RoleID>
</_x0030_3p_ActivityPersonRoles>
<_x0030_3p_ActivityPersonRoles>
<ID>69</ID>
