=== tetherless-world/POEM/rcads/data/xml/12_ComponentTypes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="_x0031_2_ComponentTypes" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="_x0031_2_ComponentTypes">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="ComponentTypeID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="GUID" type="9" value="FpRlTqsKW0++yQnt0XSuSA==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAAWlGVOqwpbT77JCe3RdK5IAAAAAK/vTV/xZOZAAAAAAAAAAAAxADIA
XwBDAG8AbQBwAG8AbgBlAG4AdABUAHkAcABlAHMAAAAAAAAAUbH1SnGUCE63j96h
r8B5EQcAAAAWlGVOqwpbT77JCe3RdK5IQwBvAG0AcABvAG4AZQBuAHQAVAB5AHAA
ZQBJAEQAAAAAAAAAFbKh49WcE0KK401WrAgJ4AcAAAAWlGVOqwpbT77JCe3RdK5I
QwBvAG0AcABvAG4AZQBuAHQAVAB5AHAAZQAAAAAAAACoshCtwp6DTIDVI9M0x4oU
BwAAABaUZU6rCltPvskJ7dF0rkhEAGEAdABhAFIAZQBjAGUAaQB2AGUAZABUAHkA
cABlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAABQAAAAAAAAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ComponentTypeID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="UbH1SnGUCE63j96hr8B5EQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ComponentType" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="FbKh49WcE0KK401WrAgJ4A==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2220"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="Description" type="10" value="A text description of the component type"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="DataReceivedType" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="3080"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="qLIQrcKeg0yA1SPTNMeKFA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== tetherless-world/POEM/rcads/data/xml/12_ComponentTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="12_ComponentTypes.xsd" generated="2025-09-22T19:02:13">
<_x0031_2_ComponentTypes>
<ComponentTypeID>1</ComponentTypeID>
<ComponentType>NameText</ComponentType>
</_x0031_2_ComponentTypes>
<_x0031_2_ComponentTypes>
<ComponentTypeID>2</ComponentTypeID>
<ComponentType>DateText</ComponentType>
</_x0031_2_ComponentTypes>
<_x0031_2_ComponentTypes>
<ComponentTypeID>3</ComponentTypeID>
<ComponentType>PageText</ComponentType>
</_x0031_2_ComponentTypes>
<_x0031_2_ComponentTypes>
<ComponentTypeID>4</ComponentTypeID>
<ComponentType>InstructionTextPaper</ComponentType>
</_x0031_2_ComponentTypes>
<_x0031_2_ComponentTypes>
<ComponentTypeID>5</ComponentTypeID>
<ComponentType>InstructionTextOnline</ComponentType>
</_x0031_2_ComponentTypes>
<_x0031_2_ComponentTypes>
<ComponentTypeID>6</ComponentTypeID>
<ComponentType>RelationshipText</ComponentType>
</_x0031_2_ComponentTypes>
<_x0031_2_ComponentTypes>
<ComponentTypeID>7</ComponentTypeID>
<ComponentType>InstructionsSubsection</ComponentType>
</_x0031_2_ComponentTypes>
<_x0031_2_ComponentTypes>
<ComponentTypeID>8</ComponentTypeID>
<ComponentType>TimeText</ComponentType>
</_x0031_2_ComponentTypes>
</dataroot>
