=== tetherless-world/POEM/rcads/data/xml/13_ComponentDataTypes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="_x0031_3_ComponentDataTypes" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="_x0031_3_ComponentDataTypes">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="ComponentDataTypeID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="GUID" type="9" value="pPwsTTA+EEeCh+giy/xyLQ==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACk/CxNMD4QR4KH6CLL/HItAAAAAGyfQFPxZOZAAAAAAAAAAAAxADMA
XwBDAG8AbQBwAG8AbgBlAG4AdABEAGEAdABhAFQAeQBwAGUAcwAAAAAAAACo4MFr
ppueS4j4E6rpElRnBwAAAKT8LE0wPhBHgofoIsv8ci1DAG8AbQBwAG8AbgBlAG4A
dABEAGEAdABhAFQAeQBwAGUASQBEAAAAAAAAAE19Dr5slYRIiVxDQRYTx9QHAAAA
pPwsTTA+EEeCh+giy/xyLUQAYQB0AGEAVAB5AHAAZQAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAADAAAAAUAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ComponentDataTypeID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="qODBa6abnkuI+BOq6RJUZw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="DataType" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="TX0OvmyVhEiJXENBFhPH1A==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== tetherless-world/POEM/rcads/data/xml/13_ComponentDataTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="13_ComponentDataTypes.xsd" generated="2025-08-28T15:31:51">
<_x0031_3_ComponentDataTypes>
<ComponentDataTypeID>1</ComponentDataTypeID>
<DataType>Integer</DataType>
</_x0031_3_ComponentDataTypes>
<_x0031_3_ComponentDataTypes>
<ComponentDataTypeID>2</ComponentDataTypeID>
<DataType>Date</DataType>
</_x0031_3_ComponentDataTypes>
<_x0031_3_ComponentDataTypes>
<ComponentDataTypeID>3</ComponentDataTypeID>
<DataType>Time</DataType>
</_x0031_3_ComponentDataTypes>
<_x0031_3_ComponentDataTypes>
<ComponentDataTypeID>4</ComponentDataTypeID>
<DataType>String</DataType>
</_x0031_3_ComponentDataTypes>
</dataroot>
