=== tetherless-world/POEM/rcads/data/xml/30_Codebooks.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="_x0033_0_Codebooks" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="_x0033_0_Codebooks">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="CodebookExperience" index-key="CodebookExperience " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="CodebookID" index-key="CodebookID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:index index-name="CodebookLanguage1" index-key="CodebookLanguage " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="CodebookName" index-key="CodebookName " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="GUID" type="9" value="u1pQh3LMGkGsSaKYDCRGdw==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAC7WlCHcswaQaxJopgMJEZ3AAAAAMSNvcOVYOZAAAAAAAAAAAAzADAA
XwBDAG8AZABlAGIAbwBvAGsAcwAAAAAAAAA1b8hzrJckTKfsGd9+lLFMAAAAANTK
0ttxZeZAAAAAAAAAAAAzADIAXwBDAG8AZABlAGIAbwBvAGsATwBwAHQAaQBvAG4A
TQBhAHAAAAAAAAAA7lnjE189Gk2ddD6FP4+/JQcAAAC7WlCHcswaQaxJopgMJEZ3
QwBvAGQAZQBiAG8AbwBrAEkARAAAAAAAAACEt8ZiilXIRLB0VNP/ePepBwAAALta
UIdyzBpBrEmimAwkRndDAG8AZABlAGIAbwBvAGsATgBhAG0AZQAAAAAAAABdFuIy
3j3MTZHtUiLtQ5L2AAAAAM4VG9cYK+ZAAAAAAAAAAAAzADMAXwBFAHgAcABlAHIA
aQBlAG4AYwBlAHMAAAAAAAAAo9XVHUvdAkSHSXsrNiQEQQcAAABdFuIy3j3MTZHt
UiLtQ5L2RQB4AHAAZQByAGkAZQBuAGMAZQBJAEQAAAAAAAAA2NJuSWbSEkiHtdze
I/PvgwcAAABdFuIy3j3MTZHtUiLtQ5L2RQB4AHAAZQByAGkAZQBuAGMAZQAAAAAA
AAD6fMl0lA4UTYJdp6hDq/yiBwAAALtaUIdyzBpBrEmimAwkRndDAG8AZABlAGIA
bwBvAGsARQB4AHAAZQByAGkAZQBuAGMAZQAAAAAAAABqYTCfkURZSY48cDc8kVA3
AAAAAKdDCscTZOZAAAAAAAAAAAA5ADAAXwBMAGEAbgBnAHUAYQBnAGUAcwAAAAAA
AACrMY2PjWV6Tp3M5t6QklJQBwAAAGphMJ+RRFlJjjxwNzyRUDdMAGEAbgBnAGEA
dQBnAGUASQBEAAAAAAAAAHO1cvlc2OxAvFlWCyVKOUUHAAAAamEwn5FEWUmOPHA3
PJFQN0wAYQBuAGcAdQBhAGcAZQAAAAAAAACeE/eDKm20SoZ/QPSDcWGsBwAAALta
UIdyzBpBrEmimAwkRndDAG8AZABlAGIAbwBvAGsATABhAG4AZwB1AGEAZwBlAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAABQAAAAAAAAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Filter" type="12" value="([Lookup_CodebookLanguage].[Language]=&quot;Urdu&quot;)"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="CodebookID" minOccurs="1" od:jetType="double" od:sqlSType="float" od:nonNullable="yes" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="General Number"/>
<od:fieldProperty name="GUID" type="9" value="7lnjE189Gk2ddD6FP4+/JQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="Description" type="10" value="A codebook is a colllection of response options having a language and an experience attribute."/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="CodebookName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="GUID" type="9" value="hLfGYopVyESwdFTT/3j3qQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="3060"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="CodebookExperience" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="+nzJdJQOFE2CXaeoQ6v8og==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2400"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [33_Experiences].ExperienceID, [33_Experiences].Experience FROM 33_Experiences ORDER BY [ExperienceID]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="CodebookLanguage" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="nhP3gypttEqGf0D0g3FhrA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2340"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [90_Languages].LangaugeID, [90_Languages].Language FROM 90_Languages ORDER BY [Language]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== tetherless-world/POEM/rcads/data/xml/30_Codebooks.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="30_Codebooks.xsd" generated="2026-02-03T10:51:23">
<_x0033_0_Codebooks>
<CodebookID>1</CodebookID>
<CodebookName>4.0-item-Frequency-English</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>1</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>2</CodebookID>
<CodebookName>4.0-item-Frequency-Arabic</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>2</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>3</CodebookID>
<CodebookName>4.0-item-Frequency-Chinese (Simplified)</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>3</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>4</CodebookID>
<CodebookName>4.0-item-Frequency-Danish</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>4</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>5</CodebookID>
<CodebookName>4.0-item-Frequency-Dutch</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>5</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>6</CodebookID>
<CodebookName>4.0-item-Frequency-Estonian</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>6</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>7</CodebookID>
<CodebookName>4.0-item-Frequency-Finnish</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>7</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>8</CodebookID>
<CodebookName>4.0-item-Frequency-French</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>8</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>9</CodebookID>
<CodebookName>4.0-item-Frequency-German</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>9</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>10</CodebookID>
<CodebookName>4.0-item-Frequency-Greek</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>10</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>11</CodebookID>
<CodebookName>4.0-item-Frequency-Hungarian</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>11</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>12</CodebookID>
<CodebookName>4.0-item-Frequency-Icelandic</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>12</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>13</CodebookID>
<CodebookName>4.0-item-Frequency-Japanese</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>13</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>14</CodebookID>
<CodebookName>4.0-item-Frequency-Korean</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>14</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>15</CodebookID>
<CodebookName>4.0-item-Frequency-Lithuanian</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>15</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>16</CodebookID>
<CodebookName>4.0-item-Frequency-Norweigan</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>16</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>17</CodebookID>
<CodebookName>4.0-item-Frequency-Persian</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>17</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>18</CodebookID>
<CodebookName>4.0-item-Frequency-Polish</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>18</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>19</CodebookID>
<CodebookName>4.0-item-Frequency-Portuguese</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>19</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>20</CodebookID>
<CodebookName>4.0-item-Frequency-Slovene</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>20</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>21</CodebookID>
<CodebookName>4.0-item-Frequency-Spanish</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>21</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>22</CodebookID>
<CodebookName>4.0-item-Frequency-Swedish</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>22</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>23</CodebookID>
<CodebookName>4.0-item-Frequency-Turkish</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>23</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>24</CodebookID>
<CodebookName>4.0-item-Frequency-Urdu</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>24</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>25</CodebookID>
<CodebookName>4.0-item-Agreement-English</CodebookName>
<CodebookExperience>5</CodebookExperience>
<CodebookLanguage>1</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>26</CodebookID>
<CodebookName>4.0-item-Agreement-Spanish</CodebookName>
<CodebookExperience>5</CodebookExperience>
<CodebookLanguage>21</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>27</CodebookID>
<CodebookName>4.1-item-Frequency-English</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>1</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>28</CodebookID>
<CodebookName>4.2-item-Frequency-English</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>1</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>29</CodebookID>
<CodebookName>4.0-item-Frequency-Swahili</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>26</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>30</CodebookID>
<CodebookName>4.0-item-Agreement-Norwegian</CodebookName>
<CodebookExperience>5</CodebookExperience>
<CodebookLanguage>16</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>31</CodebookID>
<CodebookName>4.0-item-Frequency-Hindi</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>31</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>32</CodebookID>
<CodebookName>4.1-item-Frequency-Hindi</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>31</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>33</CodebookID>
<CodebookName>4.0-item-Frequency-Punjabi</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>32</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>34</CodebookID>
<CodebookName>4.0-item-Frequency-Mongolian</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>38</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>35</CodebookID>
<CodebookName>4.2-item-Frequency-Arabic</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>2</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>36</CodebookID>
<CodebookName>4.0-item-Frequency-Marathi</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>40</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>37</CodebookID>
<CodebookName>4.0-item-Frequency-Serbian</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>27</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>38</CodebookID>
<CodebookName>4.0-item-Frequency-Vietnamese</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>39</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>39</CodebookID>
<CodebookName>4.0-item-Frequency-Italian</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>36</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>40</CodebookID>
<CodebookName>4.0-item-Frequency-Zulu</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>41</CodebookLanguage>
</_x0033_0_Codebooks>
</dataroot>

=== tetherless-world/POEM/XML/30_Codebooks.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="30_Codebooks.xsd" generated="2024-10-08T11:26:16">
<_x0033_0_Codebooks>
<CodebookID>1</CodebookID>
<CodebookName>4.0-item-Freqency-English</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>1</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>2</CodebookID>
<CodebookName>4.0-item-Freqency-Arabic</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>2</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>3</CodebookID>
<CodebookName>4.0-item-Freqency-Chinese (Simplified)</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>3</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>4</CodebookID>
<CodebookName>4.0-item-Freqency-Danish</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>4</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>5</CodebookID>
<CodebookName>4.0-item-Freqency-Dutch</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>5</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>6</CodebookID>
<CodebookName>4.0-item-Freqency-Estonian</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>6</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>7</CodebookID>
<CodebookName>4.0-item-Freqency-Finnish</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>7</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>8</CodebookID>
<CodebookName>4.0-item-Freqency-French</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>8</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>9</CodebookID>
<CodebookName>4.0-item-Freqency-German</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>9</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>10</CodebookID>
<CodebookName>4.0-item-Freqency-Greek</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>10</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>11</CodebookID>
<CodebookName>4.0-item-Freqency-Hungarian</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>11</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>12</CodebookID>
<CodebookName>4.0-item-Freqency-Icelandic</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>12</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>13</CodebookID>
<CodebookName>4.0-item-Freqency-Japanese</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>13</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>14</CodebookID>
<CodebookName>4.0-item-Freqency-Korean</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>14</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>15</CodebookID>
<CodebookName>4.0-item-Freqency-Lithuanian</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>15</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>16</CodebookID>
<CodebookName>4.0-item-Freqency-Norweigan</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>16</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>17</CodebookID>
<CodebookName>4.0-item-Freqency-Persian</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>17</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>18</CodebookID>
<CodebookName>4.0-item-Freqency-Polish</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>18</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>19</CodebookID>
<CodebookName>4.0-item-Freqency-Portuguese</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>19</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>20</CodebookID>
<CodebookName>4.0-item-Freqency-Slovene</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>20</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>21</CodebookID>
<CodebookName>4.0-item-Freqency-Spanish</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>21</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>22</CodebookID>
<CodebookName>4.0-item-Freqency-Swedish</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>22</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>23</CodebookID>
<CodebookName>4.0-item-Freqency-Turkish</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>23</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>24</CodebookID>
<CodebookName>4.0-item-Freqency-Urdu</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>24</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>25</CodebookID>
<CodebookName>4.0-item-Agreement-English</CodebookName>
<CodebookExperience>5</CodebookExperience>
<CodebookLanguage>1</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>26</CodebookID>
<CodebookName>4.0-item-Agreement-Spanish</CodebookName>
<CodebookExperience>5</CodebookExperience>
<CodebookLanguage>21</CodebookLanguage>
</_x0033_0_Codebooks>
<_x0033_0_Codebooks>
<CodebookID>27</CodebookID>
<CodebookName>4.1-item-Frequency-English</CodebookName>
<CodebookExperience>1</CodebookExperience>
<CodebookLanguage>1</CodebookLanguage>
</_x0033_0_Codebooks>
</dataroot>
