=== tetherless-world/POEM/rcads/data/xml/32_CodebookOptionMap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="_x0033_2_CodebookOptionMap" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="_x0033_2_CodebookOptionMap">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="CodebookCompID" index-key="CodebookCompID " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="GUID" type="9" value="NW/Ic6yXJEyn7BnffpSxTA==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAA1b8hzrJckTKfsGd9+lLFMAAAAABMAWCQPfuZAAAAAAAAAAAAzADIA
XwBDAG8AZABlAGIAbwBvAGsATwBwAHQAaQBvAG4ATQBhAHAAAAAAAAAAzoovUS2k
Pka2bfctESBzFQcAAAA1b8hzrJckTKfsGd9+lLFMQwBvAGQAZQBiAG8AbwBrAEMA
bwBtAHAASQBEAAAAAAAAALtaUIdyzBpBrEmimAwkRncAAAAAVE4YU7Vw5kAAAAAA
AAAAADMAMABfAEMAbwBkAGUAYgBvAG8AawBzAAAAAAAAAO5Z4xNfPRpNnXQ+hT+P
vyUHAAAAu1pQh3LMGkGsSaKYDCRGd0MAbwBkAGUAYgBvAG8AawBJAEQAAAAAAAAA
hLfGYopVyESwdFTT/3j3qQcAAAC7WlCHcswaQaxJopgMJEZ3QwBvAGQAZQBiAG8A
bwBrAE4AYQBtAGUAAAAAAAAADilodcWV3kGYhXapN4087gcAAAA1b8hzrJckTKfs
Gd9+lLFMQwBvAGQAZQBiAG8AbwBrAEkARAAAAAAAAACSOfNZwyYIR4LoBK1BP5IU
AAAAAP96Sjz1PuZAAAAAAAAAAAAzADQAXwBSAGUAcwBwAG8AbgBzAGUATwBwAHQA
aQBvAG4AQwBvAG4AYwBlAHAAdABzAAAAAAAAAFCgJd/Q/UxCmeVuj1JyLK8AAAAA
7OFVupRu5kAAAAAAAAAAADMAMQBfAFIAZQBzAHAAbwBuAHMAZQBPAHAAdABpAG8A
bgBzAAAAAAAAAJORRJHYKYZJvzGXKLBXLnoHAAAAUKAl39D9TEKZ5W6PUnIsr08A
cAB0AGkAbwBuAEkARAAAAAAAAAAG7ybIycGdRL3IFTCCZsJCBwAAAFCgJd/Q/UxC
meVuj1JyLK9PAHAAdABpAG8AbgBUAGUAeAB0AAAAAAAAAKb4VZEAuN9Ei3hHmzeC
xRkHAAAAkjnzWcMmCEeC6AStQT+SFE8AcAB0AGkAbwBuAEMAbwBuAGMAZQBwAHQA
AAAAAAAA1ahIKBGJDUCzXYWFdPyx1QcAAACSOfNZwyYIR4LoBK1BP5IUTwBwAHQA
aQBvAG4AQwBvAG4AYwBlAHAAdABJAEQAAAAAAAAAtEEnaEvktU2k6WTSu+n6zAcA
AABQoCXf0P1MQpnlbo9SciyvTwBwAHQAaQBvAG4AQwBvAG4AYwBlAHAAdABJAEQA
AAAAAAAARYvFXgwqnEKj3skv3/SDqwcAAAA1b8hzrJckTKfsGd9+lLFMTwBwAHQA
aQBvAG4ASQBEAAAAAAAAAIG5+QPxIOJHp6ohOBbQQtwHAAAANW/Ic6yXJEyn7Bnf
fpSxTE8AcAB0AGkAbwBuAFAAbwBzAGkAdABpAG8AbgAAAAAAAABPGmXkFOj3T55n
qEevuXUJBwAAADVvyHOslyRMp+wZ336UsUxPAHAAdABpAG8AbgBWAGEAbAB1AGUA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAFAAAAAAAAAAAAAAAAAAAAAAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Filter" type="12" value="([Lookup_CodebookID].[CodebookName]=&quot;4.0-item-Frequency-Portuguese&quot;)"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="CodebookCompID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="zoovUS2kPka2bfctESBzFQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2100"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="CodebookID" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="DilodcWV3kGYhXapN4087g==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="3315"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [30_Codebooks].CodebookID, [30_Codebooks].CodebookName FROM 30_Codebooks ORDER BY [CodebookName]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="OptionID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="RYvFXgwqnEKj3skv3/SDqw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [31_ResponseOptions].OptionID, [31_ResponseOptions].OptionText, [34_ResponseOptionConcepts].OptionConcept FROM 34_ResponseOptionConcepts RIGHT JOIN 31_ResponseOptions ON [34_ResponseOptionConcepts].OptionConceptID = [31_ResponseOptions].OptionConceptID ORDER BY [31_ResponseOptions].[OptionID]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="3"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1995;1920"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="3915twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="OptionPosition" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="gbn5A/Eg4kenqiE4FtBC3A==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1740"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="OptionValue" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="Txpl5BTo90+eZ6hHr7l1CQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== tetherless-world/POEM/rcads/data/xml/32_CodebookOptionMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="32_CodebookOptionMap.xsd" generated="2026-02-26T10:31:51">
<_x0033_2_CodebookOptionMap>
<CodebookCompID>101</CodebookCompID>
<CodebookID>26</CodebookID>
<OptionID>101</OptionID>
<OptionPosition>1</OptionPosition>
<OptionValue>0</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>102</CodebookCompID>
<CodebookID>26</CodebookID>
<OptionID>102</OptionID>
<OptionPosition>2</OptionPosition>
<OptionValue>1</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>103</CodebookCompID>
<CodebookID>26</CodebookID>
<OptionID>103</OptionID>
<OptionPosition>3</OptionPosition>
<OptionValue>2</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>104</CodebookCompID>
<CodebookID>26</CodebookID>
<OptionID>104</OptionID>
<OptionPosition>4</OptionPosition>
<OptionValue>3</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>105</CodebookCompID>
<CodebookID>27</CodebookID>
<OptionID>106</OptionID>
<OptionPosition>1</OptionPosition>
<OptionValue>0</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>106</CodebookCompID>
<CodebookID>27</CodebookID>
<OptionID>107</OptionID>
<OptionPosition>2</OptionPosition>
<OptionValue>1</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>107</CodebookCompID>
<CodebookID>27</CodebookID>
<OptionID>108</OptionID>
<OptionPosition>3</OptionPosition>
<OptionValue>2</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>108</CodebookCompID>
<CodebookID>27</CodebookID>
<OptionID>109</OptionID>
<OptionPosition>4</OptionPosition>
<OptionValue>3</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>1</CodebookCompID>
<CodebookID>1</CodebookID>
<OptionID>1</OptionID>
<OptionPosition>1</OptionPosition>
<OptionValue>0</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>2</CodebookCompID>
<CodebookID>1</CodebookID>
<OptionID>2</OptionID>
<OptionPosition>2</OptionPosition>
<OptionValue>1</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>3</CodebookCompID>
<CodebookID>1</CodebookID>
<OptionID>3</OptionID>
<OptionPosition>3</OptionPosition>
<OptionValue>2</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>4</CodebookCompID>
<CodebookID>1</CodebookID>
<OptionID>4</OptionID>
<OptionPosition>4</OptionPosition>
<OptionValue>3</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>5</CodebookCompID>
<CodebookID>2</CodebookID>
<OptionID>5</OptionID>
<OptionPosition>1</OptionPosition>
<OptionValue>0</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>6</CodebookCompID>
<CodebookID>2</CodebookID>
<OptionID>6</OptionID>
<OptionPosition>2</OptionPosition>
<OptionValue>1</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>7</CodebookCompID>
<CodebookID>2</CodebookID>
<OptionID>7</OptionID>
<OptionPosition>3</OptionPosition>
<OptionValue>2</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>8</CodebookCompID>
<CodebookID>2</CodebookID>
<OptionID>8</OptionID>
<OptionPosition>4</OptionPosition>
<OptionValue>3</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>9</CodebookCompID>
<CodebookID>3</CodebookID>
<OptionID>9</OptionID>
<OptionPosition>1</OptionPosition>
<OptionValue>0</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>10</CodebookCompID>
<CodebookID>3</CodebookID>
<OptionID>10</OptionID>
<OptionPosition>2</OptionPosition>
<OptionValue>1</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>11</CodebookCompID>
<CodebookID>3</CodebookID>
<OptionID>11</OptionID>
<OptionPosition>3</OptionPosition>
<OptionValue>2</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>12</CodebookCompID>
<CodebookID>3</CodebookID>
<OptionID>12</OptionID>
<OptionPosition>4</OptionPosition>
<OptionValue>3</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>13</CodebookCompID>
<CodebookID>4</CodebookID>
<OptionID>13</OptionID>
<OptionPosition>1</OptionPosition>
<OptionValue>0</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>14</CodebookCompID>
<CodebookID>4</CodebookID>
<OptionID>14</OptionID>
<OptionPosition>2</OptionPosition>
<OptionValue>1</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>15</CodebookCompID>
<CodebookID>4</CodebookID>
<OptionID>15</OptionID>
<OptionPosition>3</OptionPosition>
<OptionValue>2</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>16</CodebookCompID>
<CodebookID>4</CodebookID>
<OptionID>16</OptionID>
<OptionPosition>4</OptionPosition>
<OptionValue>3</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>17</CodebookCompID>
<CodebookID>5</CodebookID>
<OptionID>17</OptionID>
<OptionPosition>1</OptionPosition>
<OptionValue>0</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>18</CodebookCompID>
<CodebookID>5</CodebookID>
<OptionID>18</OptionID>
<OptionPosition>2</OptionPosition>
<OptionValue>1</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>19</CodebookCompID>
<CodebookID>5</CodebookID>
<OptionID>19</OptionID>
<OptionPosition>3</OptionPosition>
<OptionValue>2</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>20</CodebookCompID>
<CodebookID>5</CodebookID>
<OptionID>20</OptionID>
<OptionPosition>4</OptionPosition>
<OptionValue>3</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>21</CodebookCompID>
<CodebookID>6</CodebookID>
<OptionID>21</OptionID>
<OptionPosition>1</OptionPosition>
<OptionValue>0</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>22</CodebookCompID>
<CodebookID>6</CodebookID>
<OptionID>22</OptionID>
<OptionPosition>2</OptionPosition>
<OptionValue>1</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>23</CodebookCompID>
<CodebookID>6</CodebookID>
<OptionID>23</OptionID>
<OptionPosition>3</OptionPosition>
<OptionValue>2</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>24</CodebookCompID>
<CodebookID>6</CodebookID>
<OptionID>24</OptionID>
<OptionPosition>4</OptionPosition>
<OptionValue>3</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>25</CodebookCompID>
<CodebookID>7</CodebookID>
<OptionID>25</OptionID>
<OptionPosition>1</OptionPosition>
<OptionValue>0</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>26</CodebookCompID>
<CodebookID>7</CodebookID>
<OptionID>26</OptionID>
<OptionPosition>2</OptionPosition>
<OptionValue>1</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>27</CodebookCompID>
<CodebookID>7</CodebookID>
<OptionID>27</OptionID>
<OptionPosition>3</OptionPosition>
<OptionValue>2</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>28</CodebookCompID>
<CodebookID>7</CodebookID>
<OptionID>28</OptionID>
<OptionPosition>4</OptionPosition>
<OptionValue>3</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>29</CodebookCompID>
<CodebookID>8</CodebookID>
<OptionID>29</OptionID>
<OptionPosition>1</OptionPosition>
<OptionValue>0</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>30</CodebookCompID>
<CodebookID>8</CodebookID>
<OptionID>30</OptionID>
<OptionPosition>2</OptionPosition>
<OptionValue>1</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>31</CodebookCompID>
<CodebookID>8</CodebookID>
<OptionID>31</OptionID>
<OptionPosition>3</OptionPosition>
<OptionValue>2</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>32</CodebookCompID>
<CodebookID>8</CodebookID>
<OptionID>32</OptionID>
<OptionPosition>4</OptionPosition>
<OptionValue>3</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>33</CodebookCompID>
<CodebookID>9</CodebookID>
<OptionID>33</OptionID>
<OptionPosition>1</OptionPosition>
<OptionValue>0</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>34</CodebookCompID>
<CodebookID>9</CodebookID>
<OptionID>34</OptionID>
<OptionPosition>2</OptionPosition>
<OptionValue>1</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>35</CodebookCompID>
<CodebookID>9</CodebookID>
<OptionID>35</OptionID>
<OptionPosition>3</OptionPosition>
<OptionValue>2</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>36</CodebookCompID>
<CodebookID>9</CodebookID>
<OptionID>36</OptionID>
<OptionPosition>4</OptionPosition>
<OptionValue>3</OptionValue>
</_x0033_2_CodebookOptionMap>
<_x0033_2_CodebookOptionMap>
<CodebookCompID>37</CodebookCompID>
<CodebookID>10</CodebookID>
<OptionID>37</OptionID>
<OptionPosition>1</OptionPosition>
<OptionValue>0</OptionValue>
