=== tetherless-world/POEM/rcads/data/xml/40_Scales.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="_x0034_0_Scales" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="_x0034_0_Scales">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="ScaleID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAAqNUP9k6naSrQQc4RmoPUdAAAAAGrCRYDuVOZAAAAAAAAAAAA0ADAA
XwBTAGMAYQBsAGUAcwAAAAAAAAB/KHTsP8TtQ7P0zwa4RxsRBwAAACo1Q/2TqdpK
tBBzhGag9R1TAGMAYQBsAGUASQBEAAAAAAAAABvdq39WK9FPnoPITDH0tSMHAAAA
KjVD/ZOp2kq0EHOEZqD1HVMAYwBhAGwAZQBOAGEAbQBlAAAAAAAAAPeGPtg8uWdL
nlRB0E0abQwHAAAAKjVD/ZOp2kq0EHOEZqD1HVMAYwBhAGwAZQBDAG8AbgBzAHQA
cgB1AGMAdAAAAAAAAABvRKdTvJnhTpKJE4SirzAbBwAAACo1Q/2TqdpKtBBzhGag
9R1TAGMAYQBsAGUAVQBwAHAAZQByAEMAbwBuAHMAdAByAHUAYwB0AAAAAAAAAE7t
t+Saaf5FuvaCbRmugNgHAAAAKjVD/ZOp2kq0EHOEZqD1HUkAdABlAG0ATgAAAAAA
AABN4BiAYlqiTpGl6KCam0DMBwAAACo1Q/2TqdpKtBBzhGag9R1TAGMAYQBsAGUA
UwBoAG8AcgB0AE4AYQBtAGUAAAAAAAAAD60xO2XxB0ezyPItayUA8wcAAAAqNUP9
k6naSrQQc4RmoPUdUwBjAGEAbABlAEkAbgBpAHQAaQBhAGwAcwAAAAAAAACD0ZBt
O2vGRK77zX+x+8HeAAAAACZHiu8yYuZAAAAAAAAAAAAwADAAXwBJAG4AcwB0AHIA
dQBtAGUAbgB0AEYAYQBtAGkAbABpAGUAcwAAAAAAAAB+8/7JF/cqT6ikgI0Wn9Ny
BwAAAIPRkG07a8ZErvvNf7H7wd5GAGEAbQBpAGwAeQBJAEQAAAAAAAAA1KmKYvfJ
2EyPNGlsjyEJMAcAAACD0ZBtO2vGRK77zX+x+8HeSQBuAHMAdAByAHUAbQBlAG4A
dABGAGEAbQBpAGwAeQAAAAAAAACCD3YoBzbKRYzaUMJ4dYIxBwAAACo1Q/2TqdpK
tBBzhGag9R1JAG4AcwB0AHIAdQBtAGUAbgB0AEMAbwBsAGwAZQBjAHQAaQBvAG4A
AAAAAAAAq6Vy4zYuSUa3ImqUy6YzsgcAAAAqNUP9k6naSrQQc4RmoPUdSQBuAHMA
dAByAHUAbQBlAG4AdABMAGUAbgBnAHQAaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DAAAAAUAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="GUID" type="9" value="KjVD/ZOp2kq0EHOEZqD1HQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ScaleID" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="fyh07D/E7UOz9M8GuEcbEQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ScaleName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="5115"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="G92rf1Yr0U+eg8hMMfS1Iw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="ScaleConstruct" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2445"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="94Y+2Dy5Z0ueVEHQTRptDA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="ScaleUpperConstruct" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2805"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="b0SnU7yZ4U6SiROEoq8wGw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="ItemN" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="Description" type="10" value="This can be removed. It is an emergent property that can be calculated from the ItemScale table (which we need)"/>
<od:fieldProperty name="GUID" type="9" value="Tu235Jpp/kW69oJtGa6A2A==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ScaleShortName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="TeAYgGJaok6RpeigmptAzA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="5100"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="ScaleInitials" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="D60xO2XxB0ezyPItayUA8w==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="InstrumentCollection" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="gg92KAc2ykWM2lDCeHWCMQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [00_InstrumentFamilies].[FamilyID], [00_InstrumentFamilies].[InstrumentFamily] FROM 00_InstrumentFamilies ORDER BY [InstrumentFamily]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="Description" type="10" value="This is a faster way of determining which instrument a scale belongs to than the real way of computing relationships through instruments, items, item concepts, &amp; scales."/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="InstrumentLength" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="q6Vy4zYuSUa3ImqUy6Yzsg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="This is the length of the instrument in the instrument collection to which the scale belongs."/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== tetherless-world/POEM/rcads/data/xml/40_Scales.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="40_Scales.xsd" generated="2025-09-22T19:06:01">
<_x0034_0_Scales>
<ScaleID>1</ScaleID>
<ScaleName>Social Phobia (9.1)</ScaleName>
<ScaleConstruct>Social Anxiety</ScaleConstruct>
<ScaleUpperConstruct>Anxiety</ScaleUpperConstruct>
<ItemN>9</ItemN>
<ScaleShortName>Social Phobia</ScaleShortName>
<ScaleInitials>SP</ScaleInitials>
<InstrumentCollection>1</InstrumentCollection>
<InstrumentLength>47</InstrumentLength>
</_x0034_0_Scales>
<_x0034_0_Scales>
<ScaleID>2</ScaleID>
<ScaleName>Panic Disorder (9.1)</ScaleName>
<ScaleConstruct>Panic</ScaleConstruct>
<ScaleUpperConstruct>Anxiety</ScaleUpperConstruct>
<ItemN>9</ItemN>
<ScaleShortName>Panic Disorder</ScaleShortName>
<ScaleInitials>PD</ScaleInitials>
<InstrumentCollection>1</InstrumentCollection>
<InstrumentLength>47</InstrumentLength>
</_x0034_0_Scales>
<_x0034_0_Scales>
<ScaleID>3</ScaleID>
<ScaleName>Generalized Anxiety Disorder (6.1)</ScaleName>
<ScaleConstruct>Worry</ScaleConstruct>
<ScaleUpperConstruct>Anxiety</ScaleUpperConstruct>
<ItemN>6</ItemN>
<ScaleShortName>Generalized Anxiety Disorder</ScaleShortName>
<ScaleInitials>GAD</ScaleInitials>
<InstrumentCollection>1</InstrumentCollection>
<InstrumentLength>47</InstrumentLength>
</_x0034_0_Scales>
<_x0034_0_Scales>
<ScaleID>4</ScaleID>
<ScaleName>Major Depressive Disorder (10.1)</ScaleName>
<ScaleConstruct>Depressed Mood</ScaleConstruct>
<ScaleUpperConstruct>Depression</ScaleUpperConstruct>
<ItemN>10</ItemN>
<ScaleShortName>Major Depressive Disorder</ScaleShortName>
<ScaleInitials>MDD</ScaleInitials>
<InstrumentCollection>1</InstrumentCollection>
<InstrumentLength>25</InstrumentLength>
</_x0034_0_Scales>
<_x0034_0_Scales>
<ScaleID>5</ScaleID>
<ScaleName>Separation Anxiety Disorder (7.1)</ScaleName>
<ScaleConstruct>Separation Anxiety</ScaleConstruct>
<ScaleUpperConstruct>Anxiety</ScaleUpperConstruct>
<ItemN>7</ItemN>
<ScaleShortName>Separation Anxiety Disorder</ScaleShortName>
<ScaleInitials>SAD</ScaleInitials>
<InstrumentCollection>1</InstrumentCollection>
<InstrumentLength>47</InstrumentLength>
</_x0034_0_Scales>
<_x0034_0_Scales>
<ScaleID>6</ScaleID>
<ScaleName>Obsessive Compulsive Disorder (6.1)</ScaleName>
<ScaleConstruct>OCD</ScaleConstruct>
<ScaleUpperConstruct>Anxiety</ScaleUpperConstruct>
<ItemN>6</ItemN>
<ScaleShortName>Obsessive Compulsive Disorder</ScaleShortName>
<ScaleInitials>OCD</ScaleInitials>
<InstrumentCollection>1</InstrumentCollection>
<InstrumentLength>47</InstrumentLength>
</_x0034_0_Scales>
<_x0034_0_Scales>
<ScaleID>7</ScaleID>
<ScaleName>Total Anxiety (37.1)</ScaleName>
<ScaleConstruct>Anxiety</ScaleConstruct>
<ScaleUpperConstruct>Anxiety</ScaleUpperConstruct>
<ItemN>37</ItemN>
<ScaleShortName>Total Anxiety (37.1)</ScaleShortName>
<ScaleInitials>ANX</ScaleInitials>
<InstrumentCollection>1</InstrumentCollection>
<InstrumentLength>47</InstrumentLength>
</_x0034_0_Scales>
<_x0034_0_Scales>
<ScaleID>8</ScaleID>
<ScaleName>Total Anxiety and Depression (47.1)</ScaleName>
<ScaleConstruct>Negative Affect</ScaleConstruct>
<ScaleUpperConstruct>Negative Affect</ScaleUpperConstruct>
<ItemN>47</ItemN>
<ScaleShortName>Total Anxiety and Depression (47.1)</ScaleShortName>
<ScaleInitials>ANXDEP</ScaleInitials>
<InstrumentCollection>1</InstrumentCollection>
<InstrumentLength>47</InstrumentLength>
</_x0034_0_Scales>
<_x0034_0_Scales>
<ScaleID>9</ScaleID>
<ScaleName>Total Anxiety (15.1)</ScaleName>
<ScaleConstruct>Anxiety</ScaleConstruct>
<ScaleUpperConstruct>Anxiety</ScaleUpperConstruct>
<ItemN>15</ItemN>
<ScaleShortName>Total Anxiety (15.1)</ScaleShortName>
<ScaleInitials>Anx15</ScaleInitials>
<InstrumentCollection>1</InstrumentCollection>
<InstrumentLength>25</InstrumentLength>
</_x0034_0_Scales>
<_x0034_0_Scales>
<ScaleID>10</ScaleID>
<ScaleName>Total Anxiety and Depression (25.1)</ScaleName>
<ScaleConstruct>Negative Affect</ScaleConstruct>
<ScaleUpperConstruct>Negative Affect</ScaleUpperConstruct>
<ItemN>25</ItemN>
<ScaleShortName>Total Anxiety and Depression (25.1)</ScaleShortName>
<ScaleInitials>AnxDep25</ScaleInitials>
<InstrumentCollection>1</InstrumentCollection>
<InstrumentLength>25</InstrumentLength>
</_x0034_0_Scales>
<_x0034_0_Scales>
<ScaleID>11</ScaleID>
<ScaleName>Total Depression (5.1)</ScaleName>
<ScaleConstruct>Depression</ScaleConstruct>
<ScaleUpperConstruct>Depression</ScaleUpperConstruct>
<ItemN>5</ItemN>
<ScaleShortName>Total Depression (5.1)</ScaleShortName>
<ScaleInitials>Dep5</ScaleInitials>
<InstrumentCollection>1</InstrumentCollection>
</_x0034_0_Scales>
<_x0034_0_Scales>
<ScaleID>12</ScaleID>
<ScaleName>Total Anxiety (20.1)</ScaleName>
<ScaleConstruct>Anxiety</ScaleConstruct>
<ScaleUpperConstruct>Anxiety</ScaleUpperConstruct>
<ItemN>20</ItemN>
<ScaleShortName>Total Anxiety (20.1)</ScaleShortName>
<ScaleInitials>Anx20</ScaleInitials>
<InstrumentCollection>1</InstrumentCollection>
</_x0034_0_Scales>
<_x0034_0_Scales>
<ScaleID>13</ScaleID>
<ScaleName>Relationship (7.1)</ScaleName>
<ScaleConstruct>Relationship</ScaleConstruct>
<ScaleUpperConstruct>Engagement</ScaleUpperConstruct>
<ItemN>7</ItemN>
<ScaleShortName>Relationship</ScaleShortName>
<ScaleInitials>R</ScaleInitials>
<InstrumentCollection>3</InstrumentCollection>
<InstrumentLength>35</InstrumentLength>
</_x0034_0_Scales>
<_x0034_0_Scales>
<ScaleID>14</ScaleID>
<ScaleName>Expectancy (7.1)</ScaleName>
<ScaleConstruct>Expectancy</ScaleConstruct>
<ScaleUpperConstruct>Engagement</ScaleUpperConstruct>
<ItemN>7</ItemN>
<ScaleShortName>Expectancy</ScaleShortName>
<ScaleInitials>E</ScaleInitials>
<InstrumentCollection>3</InstrumentCollection>
<InstrumentLength>35</InstrumentLength>
</_x0034_0_Scales>
<_x0034_0_Scales>
<ScaleID>15</ScaleID>
<ScaleName>Attendance (7.1)</ScaleName>
<ScaleConstruct>Attendance</ScaleConstruct>
<ScaleUpperConstruct>Engagement</ScaleUpperConstruct>
<ItemN>7</ItemN>
<ScaleShortName>Attendance</ScaleShortName>
<ScaleInitials>A</ScaleInitials>
<InstrumentCollection>3</InstrumentCollection>
<InstrumentLength>35</InstrumentLength>
</_x0034_0_Scales>
<_x0034_0_Scales>
<ScaleID>16</ScaleID>
<ScaleName>Clarity (7.1)</ScaleName>
<ScaleConstruct>Clarity</ScaleConstruct>
<ScaleUpperConstruct>Engagement</ScaleUpperConstruct>
<ItemN>7</ItemN>
<ScaleShortName>Clarity</ScaleShortName>
<ScaleInitials>C</ScaleInitials>
<InstrumentCollection>3</InstrumentCollection>
<InstrumentLength>35</InstrumentLength>
</_x0034_0_Scales>
<_x0034_0_Scales>
<ScaleID>17</ScaleID>
<ScaleName>Homework (7.1)</ScaleName>
<ScaleConstruct>Homework</ScaleConstruct>
<ScaleUpperConstruct>Engagement</ScaleUpperConstruct>
<ItemN>7</ItemN>
<ScaleShortName>Homework</ScaleShortName>
<ScaleInitials>H</ScaleInitials>
<InstrumentCollection>3</InstrumentCollection>
<InstrumentLength>35</InstrumentLength>
</_x0034_0_Scales>
<_x0034_0_Scales>
<ScaleID>18</ScaleID>
<ScaleName>Depression (9.1)</ScaleName>
<ScaleConstruct>Depression</ScaleConstruct>
<ScaleUpperConstruct>Negative Affect</ScaleUpperConstruct>
<ItemN>9</ItemN>
<ScaleShortName>Depression (9.1)</ScaleShortName>
<ScaleInitials>PHQ-9-Dep</ScaleInitials>
<InstrumentCollection>4</InstrumentCollection>
<InstrumentLength>9</InstrumentLength>
</_x0034_0_Scales>
</dataroot>
