=== tetherless-world/POEM/rcads/data/xml/71_ScaleSystemMapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="_x0037_1_ScaleSystemMapping" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="_x0037_1_ScaleSystemMapping">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="Code" index-key="Code " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ScaleSystemMapID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:index index-name="SystemID" index-key="SystemID " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACO5FLUxvPrT6rBL5nnxvMlAAAAALodfVWSXuZAAAAAAAAAAAA3ADAA
XwBTAGMAYQBsAGUAUwB5AHMAdABlAG0ATQBhAHAAcABpAG4AZwAAAAAAAABhj448
6L1cTrsUxRdIq81pBwAAAI7kUtTG8+tPqsEvmefG8yVTAGMAYQBsAGUAUwB5AHMA
dABlAG0ATQBhAHAASQBEAAAAAAAAACo1Q/2TqdpKtBBzhGag9R0AAAAAasJFgO5U
5kAAAAAAAAAAADQAMABfAFMAYwBhAGwAZQBzAAAAAAAAAH8odOw/xO1Ds/TPBrhH
GxEHAAAAKjVD/ZOp2kq0EHOEZqD1HVMAYwBhAGwAZQBJAEQAAAAAAAAAG92rf1Yr
0U+eg8hMMfS1IwcAAAAqNUP9k6naSrQQc4RmoPUdUwBjAGEAbABlAE4AYQBtAGUA
AAAAAAAAF+imcXjQEEu+C1kEqfL0VQcAAACO5FLUxvPrT6rBL5nnxvMlUwBjAGEA
bABlAEkARAAAAAAAAAAVr7buGtgESqXPtEho20KHAAAAAI3c+0OSXuZAAAAAAAAA
AAA3ADAAXwBUAGUAcgBtAGkAbgBvAGwAbwBnAHkAUwB5AHMAdABlAG0AcwAAAAAA
AACr7tdjzAh3R5LpVGpBRbFQBwAAABWvtu4a2ARKpc+0SGjbQodTAHkAcwB0AGUA
bQBJAEQAAAAAAAAAU+vGJjmWAEKPMLWVaBRDfAcAAAAVr7buGtgESqXPtEho20KH
UwB5AHMAdABlAG0ATgBhAG0AZQAAAAAAAAC0+qmWVEt/SJvm+DiVXCcOBwAAAI7k
UtTG8+tPqsEvmefG8yVTAHkAcwB0AGUAbQBJAEQAAAAAAAAAiRB5DgVyVUe+winT
0PkogQcAAACO5FLUxvPrT6rBL5nnxvMlQwBvAGQAZQAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAADAAAAAUAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="juRS1Mbz60+qwS+Z58bzJQ==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ScaleSystemMapID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="YY+OPOi9XE67FMUXSKvNaQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ScaleID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="F+imcXjQEEu+C1kEqfL0VQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="4725"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [40_Scales].[ScaleID], [40_Scales].[ScaleName] FROM 40_Scales ORDER BY [ScaleName]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="SystemID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="tPqpllRLf0ib5vg4lVwnDg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [70_TerminologySystems].[SystemID], [70_TerminologySystems].[SystemName] FROM 70_TerminologySystems ORDER BY [SystemName]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Code" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="iRB5DgVyVUe+winT0PkogQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1920"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== tetherless-world/POEM/rcads/data/xml/71_ScaleSystemMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="71_ScaleSystemMapping.xsd" generated="2025-07-15T15:44:45">
<_x0037_1_ScaleSystemMapping>
<ScaleSystemMapID>1</ScaleSystemMapID>
<ScaleID>3</ScaleID>
<SystemID>1</SystemID>
<Code>SCTID: 21897009</Code>
</_x0037_1_ScaleSystemMapping>
<_x0037_1_ScaleSystemMapping>
<ScaleSystemMapID>2</ScaleSystemMapID>
<ScaleID>4</ScaleID>
<SystemID>1</SystemID>
<Code>SCTID: 370143000</Code>
</_x0037_1_ScaleSystemMapping>
<_x0037_1_ScaleSystemMapping>
<ScaleSystemMapID>3</ScaleSystemMapID>
<ScaleID>2</ScaleID>
<SystemID>1</SystemID>
<Code>SCTID: 371631005</Code>
</_x0037_1_ScaleSystemMapping>
<_x0037_1_ScaleSystemMapping>
<ScaleSystemMapID>4</ScaleSystemMapID>
<ScaleID>1</ScaleID>
<SystemID>1</SystemID>
<Code>SCTID: 25501002</Code>
</_x0037_1_ScaleSystemMapping>
<_x0037_1_ScaleSystemMapping>
<ScaleSystemMapID>5</ScaleSystemMapID>
<ScaleID>5</ScaleID>
<SystemID>1</SystemID>
<Code>SCTID: 126943008</Code>
</_x0037_1_ScaleSystemMapping>
<_x0037_1_ScaleSystemMapping>
<ScaleSystemMapID>6</ScaleSystemMapID>
<ScaleID>18</ScaleID>
<SystemID>1</SystemID>
<Code>SCTID: 370143000</Code>
</_x0037_1_ScaleSystemMapping>
<_x0037_1_ScaleSystemMapping>
<ScaleSystemMapID>7</ScaleSystemMapID>
<ScaleID>6</ScaleID>
<SystemID>1</SystemID>
<Code>SCTID: 191736004</Code>
</_x0037_1_ScaleSystemMapping>
</dataroot>
