=== tetherless-world/POEM/rcads/data/xml/72_ItemConceptSystemMapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="_x0037_2_ItemConceptSystemMapping" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="_x0037_2_ItemConceptSystemMapping">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="Code" index-key="Code " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="CodeDescription (optional)" index-key="LocalDescription " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="ItemConceptID" index-key="ItemStemConceptID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ItemStemConceptSystemMapID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:index index-name="SystemID" index-key="SystemID " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAABKfRXoFT/7QJjZbmLtXSPqAAAAAMb+i42WYOZAAAAAAAAAAAA3ADIA
XwBJAHQAZQBtAEMAbwBuAGMAZQBwAHQAUwB5AHMAdABlAG0ATQBhAHAAcABpAG4A
ZwAAAAAAAACY9t1vtHm2S6qGg7HSn3MbBwAAAEp9FegVP/tAmNluYu1dI+pJAHQA
ZQBtAFMAdABlAG0AQwBvAG4AYwBlAHAAdABTAHkAcwB0AGUAbQBNAGEAcABJAEQA
AAAAAAAAqvz/V13j00istGPCsoKrBAAAAACJRlCicj/mQAAAAAAAAAAAMgAyAF8A
SQB0AGUAbQBTAHQAZQBtAEMAbwBuAGMAZQBwAHQAcwAAAAAAAAC+ADGYmdTmSJZ6
xqEof34gBwAAAKr8/1dd49NIrLRjwrKCqwRJAHQAZQBtAFMAdABlAG0AQwBvAG4A
YwBlAHAAdABJAEQAAAAAAAAAhVGxv3FSC0+LAc2nwBSYRwcAAACq/P9XXePTSKy0
Y8KygqsESQB0AGUAbQBTAHQAZQBtAEMAbwBuAGMAZQBwAHQAAAAAAAAAFEOK7d7x
PUqgqZCeUsxeqgcAAABKfRXoFT/7QJjZbmLtXSPqSQB0AGUAbQBTAHQAZQBtAEMA
bwBuAGMAZQBwAHQASQBEAAAAAAAAABWvtu4a2ARKpc+0SGjbQocAAAAAjdz7Q5Je
5kAAAAAAAAAAADcAMABfAFQAZQByAG0AaQBuAG8AbABvAGcAeQBTAHkAcwB0AGUA
bQBzAAAAAAAAAKvu12PMCHdHkulUakFFsVAHAAAAFa+27hrYBEqlz7RIaNtCh1MA
eQBzAHQAZQBtAEkARAAAAAAAAABT68YmOZYAQo8wtZVoFEN8BwAAABWvtu4a2ARK
pc+0SGjbQodTAHkAcwB0AGUAbQBOAGEAbQBlAAAAAAAAAPGdsk566mpBpgXubmUl
ZY8HAAAASn0V6BU/+0CY2W5i7V0j6lMAeQBzAHQAZQBtAEkARAAAAAAAAADeTMnj
L2heQJz/r/ErbkJJBwAAAEp9FegVP/tAmNluYu1dI+pDAG8AZABlAAAAAAAAAC7U
NWqSwjBMlMULQGWiNEEHAAAASn0V6BU/+0CY2W5i7V0j6kwAbwBjAGEAbABEAGUA
cwBjAHIAaQBwAHQAaQBvAG4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAFAAAA
AAAAAAAAAAAAAAAAAAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="GUID" type="9" value="Sn0V6BU/+0CY2W5i7V0j6g==
"/>
<od:tableProperty name="Filter" type="12" value="([Lookup_ItemStemConceptID].[ItemStemConcept]=&quot;Feels nothing is much fun anymore, loss of pleasure or interest&quot;)"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ItemStemConceptSystemMapID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1305"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="mPbdb7R5tkuqhoOx0p9zGw==
"/>
<od:fieldProperty name="Description" type="10" value="This table indicates associated targets with item concepts. These are rational associations (face validity), not necessarily empirical ones."/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ItemStemConceptID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="4950"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [22_ItemStemConcepts].[ItemStemConceptID], [22_ItemStemConcepts].[ItemStemConcept] FROM 22_ItemStemConcepts ORDER BY [ItemStemConceptID]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;3645"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="3645twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="1"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="FEOK7d7xPUqgqZCeUsxeqg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="SystemID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [70_TerminologySystems].[SystemID], [70_TerminologySystems].[SystemName] FROM 70_TerminologySystems ORDER BY [SystemName]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="8Z2yTnrqakGmBe5uZSVljw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Code" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2595"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="3kzJ4y9oXkCc/6/xK25CSQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="LocalDescription" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="LtQ1apLCMEyUxQtAZaI0QQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="4425"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="Put this here for quick reference, but all terms are stored in the external system and should be referenced, not stored here as well"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== tetherless-world/POEM/rcads/data/xml/72_ItemConceptSystemMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="72_ItemConceptSystemMapping.xsd" generated="2025-07-15T15:44:56">
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>52</ItemStemConceptSystemMapID>
<ItemStemConceptID>84</ItemStemConceptID>
<SystemID>1</SystemID>
<Code>SCTID: 420038007</Code>
<LocalDescription>feeling unhappy</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>53</ItemStemConceptSystemMapID>
<ItemStemConceptID>85</ItemStemConceptID>
<SystemID>1</SystemID>
<Code>SCTID: 26677001</Code>
<LocalDescription>sleep pattern disturbance</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>54</ItemStemConceptSystemMapID>
<ItemStemConceptID>84</ItemStemConceptID>
<SystemID>1</SystemID>
<Code>SCTID: 1217332007</Code>
<LocalDescription>persistent sadness</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>55</ItemStemConceptSystemMapID>
<ItemStemConceptID>85</ItemStemConceptID>
<SystemID>1</SystemID>
<Code>SCTID: 53888004</Code>
<LocalDescription>disturbance in sleep behavior</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>56</ItemStemConceptSystemMapID>
<ItemStemConceptID>21</ItemStemConceptID>
<SystemID>1</SystemID>
<Code>SCTID: 26677001</Code>
<LocalDescription>sleep pattern disturbance</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>57</ItemStemConceptSystemMapID>
<ItemStemConceptID>12</ItemStemConceptID>
<SystemID>1</SystemID>
<Code>SCTID: 1217332007</Code>
<LocalDescription>persistent sadness</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>58</ItemStemConceptSystemMapID>
<ItemStemConceptID>31</ItemStemConceptID>
<SystemID>1</SystemID>
<Code>SCTID: 102912007</Code>
<LocalDescription>fear of death</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>59</ItemStemConceptSystemMapID>
<ItemStemConceptID>10</ItemStemConceptID>
<SystemID>1</SystemID>
<Code>SCTID: 28669007</Code>
<LocalDescription>anhedonia</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>60</ItemStemConceptSystemMapID>
<ItemStemConceptID>4</ItemStemConceptID>
<SystemID>1</SystemID>
<Code>SCTID: 67698009</Code>
<LocalDescription>obsessional thoughts</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>61</ItemStemConceptSystemMapID>
<ItemStemConceptID>5</ItemStemConceptID>
<SystemID>1</SystemID>
<Code>SCTID: 64336009</Code>
<LocalDescription>incoherent thinking</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>62</ItemStemConceptSystemMapID>
<ItemStemConceptID>6</ItemStemConceptID>
<SystemID>1</SystemID>
<Code>SCTID: 67698009</Code>
<LocalDescription>obsessional thoughts</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>63</ItemStemConceptSystemMapID>
<ItemStemConceptID>23</ItemStemConceptID>
<SystemID>1</SystemID>
<Code>SCTID: 247963001</Code>
<LocalDescription>compulsive checking</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>64</ItemStemConceptSystemMapID>
<ItemStemConceptID>37</ItemStemConceptID>
<SystemID>2</SystemID>
<Code>A</Code>
<LocalDescription>Excessive anxiety and worry more days than not for at least 6 months</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>65</ItemStemConceptSystemMapID>
<ItemStemConceptID>12</ItemStemConceptID>
<SystemID>2</SystemID>
<Code>A1</Code>
<LocalDescription>Depressed mood most of the day nearly every day</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>66</ItemStemConceptSystemMapID>
<ItemStemConceptID>35</ItemStemConceptID>
<SystemID>2</SystemID>
<Code>A1</Code>
<LocalDescription>Recurrent unexpected Panic Attacks</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>67</ItemStemConceptSystemMapID>
<ItemStemConceptID>45</ItemStemConceptID>
<SystemID>2</SystemID>
<Code>A</Code>
<LocalDescription>Marked fear/anxiety about social situations where individual is exposed to unfamiliar peole or to possible scrutiny by others. Fears they will act in a way or show anxiety symptoms that will be humiliating or embarassing.</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>68</ItemStemConceptSystemMapID>
<ItemStemConceptID>7</ItemStemConceptID>
<SystemID>2</SystemID>
<Code>A1</Code>
<LocalDescription>Recurrent excessive distress when anticipating/experiencing separation from home or other major attachment figures</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>69</ItemStemConceptSystemMapID>
<ItemStemConceptID>10</ItemStemConceptID>
<SystemID>2</SystemID>
<Code>A2</Code>
<LocalDescription>Markedly diminished interest or pleasure in all or almost all activities most of the day, nearly every day</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>70</ItemStemConceptSystemMapID>
<ItemStemConceptID>26</ItemStemConceptID>
<SystemID>2</SystemID>
<Code>A</Code>
<LocalDescription>Marked fear/anxiety about social situations where individual is exposed to unfamiliar peole or to possible scrutiny by others. Fears they will act in a way or show anxiety symptoms that will be humiliating or embarassing.</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>71</ItemStemConceptSystemMapID>
<ItemStemConceptID>14</ItemStemConceptID>
<SystemID>2</SystemID>
<Code>A</Code>
<LocalDescription>Marked fear/anxiety about social situations where individual is exposed to unfamiliar peole or to possible scrutiny by others. Fears they will act in a way or show anxiety symptoms that will be humiliating or embarassing.</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>72</ItemStemConceptSystemMapID>
<ItemStemConceptID>8</ItemStemConceptID>
<SystemID>2</SystemID>
<Code>A1</Code>
<LocalDescription>Recurrent excessive distress when anticipating/experiencing separation from home or other major attachment figures</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>73</ItemStemConceptSystemMapID>
<ItemStemConceptID>4</ItemStemConceptID>
<SystemID>2</SystemID>
<Code>A_O</Code>
<LocalDescription>Presence of obsessions: recurrent/persistent thoughts, urges, or images that are experienced as intrusive and unwanted that cause marked anxiety/distress. Individual attempts to ignore or suppress such thoughts, urges or images or to neutralize them with </LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>74</ItemStemConceptSystemMapID>
<ItemStemConceptID>21</ItemStemConceptID>
<SystemID>2</SystemID>
<Code>A4</Code>
<LocalDescription>Insomnia or hypersomnia nearly every day</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>75</ItemStemConceptSystemMapID>
<ItemStemConceptID>46</ItemStemConceptID>
<SystemID>2</SystemID>
<Code>A</Code>
<LocalDescription>Marked fear/anxiety about social situations where individual is exposed to unfamiliar peole or to possible scrutiny by others. Fears they will act in a way or show anxiety symptoms that will be humiliating or embarassing.</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>76</ItemStemConceptSystemMapID>
<ItemStemConceptID>42</ItemStemConceptID>
<SystemID>2</SystemID>
<Code>A</Code>
<LocalDescription>Excessive anxiety and worry more days than not for at least 6 months</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>77</ItemStemConceptSystemMapID>
<ItemStemConceptID>29</ItemStemConceptID>
<SystemID>2</SystemID>
<Code>A1</Code>
<LocalDescription>Recurrent unexpected Panic Attacks</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>78</ItemStemConceptSystemMapID>
<ItemStemConceptID>17</ItemStemConceptID>
<SystemID>2</SystemID>
<Code>A3</Code>
<LocalDescription>Significant weight loss or weight gain</LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>79</ItemStemConceptSystemMapID>
<ItemStemConceptID>23</ItemStemConceptID>
<SystemID>2</SystemID>
<Code>A_C</Code>
<LocalDescription>Repetitive behaviors or mental acts that the individual feels driven to perform in response to an obsession or according to rules that must be applied rigidly. </LocalDescription>
</_x0037_2_ItemConceptSystemMapping>
<_x0037_2_ItemConceptSystemMapping>
<ItemStemConceptSystemMapID>80</ItemStemConceptSystemMapID>
<ItemStemConceptID>24</ItemStemConceptID>
