=== tetherless-world/POEM/rcads/data/xml/82_AgentPersonMap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="_x0038_2_AgentPersonMap" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="_x0038_2_AgentPersonMap">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="AuthorGroupID" index-key="AgentPersonMapID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="AgentPersonMapID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACJ3fwt/zE6QrzPRkMG41XaAAAAAFRB4x2VYOZAAAAAAAAAAAA4ADIA
XwBBAGcAZQBuAHQAUABlAHIAcwBvAG4ATQBhAHAAMQAAAAAAAACTN2UgJWOeR6RS
DbSqw9otBwAAAInd/C3/MTpCvM9GQwbjVdpBAGcAZQBuAHQAUABlAHIAcwBvAG4A
TQBhAHAASQBEAAAAAAAAAPDbO3kGcQ1EgDUTVQ0/6soAAAAAi2Y9Hc9a5kAAAAAA
AAAAADgAMQBfAEEAZwBlAG4AdABzAAAAAAAAALc6MaUUoU9Fl/vo3BqPpSUHAAAA
8Ns7eQZxDUSANRNVDT/qykEAZwBlAG4AdABJAEQAAAAAAAAARd/lm3GFxk+A2TV9
8ImbKQcAAADw2zt5BnENRIA1E1UNP+rKQQBnAGUAbgB0AE4AYQBtAGUAAAAAAAAA
/tO3A6qSxEm7+enqIueU5AcAAACJ3fwt/zE6QrzPRkMG41XaQQBnAGUAbgB0AAAA
AAAAAARMfgH6G6VGr/175LECqK0AAAAAf0I8Hc9a5kAAAAAAAAAAADgAMABfAFAA
ZQByAHMAbwBuAHMAAAAAAAAA22+mLr8tv0uE+Q5X0b2R/gcAAAAETH4B+hulRq/9
e+SxAqitUABlAHIAcwBvAG4ASQBEAAAAAAAAAOjdgGH5MI5KiepqJ2vKSYMHAAAA
BEx+AfobpUav/XvksQKorVAAZQByAHMAbwBuAE4AYQBtAGUAAAAAAAAAWFVVvUeP
nE6+NOebGEBUggcAAACJ3fwt/zE6QrzPRkMG41XaUABlAHIAcwBvAG4AAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAwAAAAFAAAAAAAAAAAAAAAAAAAAAAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="GUID" type="9" value="id38Lf8xOkK8z0ZDBuNV2g==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="AgentPersonMapID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2235"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="kzdlICVjnkekUg20qsPaLQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Agent" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="4095"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [81_Agents].[AgentID], [81_Agents].[AgentName] FROM 81_Agents ORDER BY [AgentName]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="/tO3A6qSxEm7+enqIueU5A==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Person" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2190"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [80_Persons].[PersonID], [80_Persons].[PersonName] FROM 80_Persons ORDER BY [PersonName]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="WFVVvUePnE6+NOebGEBUgg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== tetherless-world/POEM/rcads/data/xml/82_AgentPersonMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="82_AgentPersonMap.xsd" generated="2025-09-22T19:07:51">
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>1</AgentPersonMapID>
<Agent>1</Agent>
<Person>1</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>2</AgentPersonMapID>
<Agent>1</Agent>
<Person>2</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>3</AgentPersonMapID>
<Agent>2</Agent>
<Person>1</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>4</AgentPersonMapID>
<Agent>2</Agent>
<Person>3</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>5</AgentPersonMapID>
<Agent>3</Agent>
<Person>4</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>6</AgentPersonMapID>
<Agent>5</Agent>
<Person>5</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>7</AgentPersonMapID>
<Agent>5</Agent>
<Person>6</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>8</AgentPersonMapID>
<Agent>5</Agent>
<Person>1</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>9</AgentPersonMapID>
<Agent>5</Agent>
<Person>7</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>10</AgentPersonMapID>
<Agent>5</Agent>
<Person>8</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>11</AgentPersonMapID>
<Agent>5</Agent>
<Person>9</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>12</AgentPersonMapID>
<Agent>5</Agent>
<Person>10</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>13</AgentPersonMapID>
<Agent>5</Agent>
<Person>11</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>14</AgentPersonMapID>
<Agent>6</Agent>
<Person>5</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>15</AgentPersonMapID>
<Agent>6</Agent>
<Person>13</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>16</AgentPersonMapID>
<Agent>6</Agent>
<Person>12</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>17</AgentPersonMapID>
<Agent>6</Agent>
<Person>1</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>18</AgentPersonMapID>
<Agent>6</Agent>
<Person>11</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>19</AgentPersonMapID>
<Agent>3</Agent>
<Person>1</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>20</AgentPersonMapID>
<Agent>3</Agent>
<Person>3</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>21</AgentPersonMapID>
<Agent>7</Agent>
<Person>1</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>22</AgentPersonMapID>
<Agent>7</Agent>
<Person>15</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>23</AgentPersonMapID>
<Agent>8</Agent>
<Person>14</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>24</AgentPersonMapID>
<Agent>8</Agent>
<Person>5</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>26</AgentPersonMapID>
<Agent>8</Agent>
<Person>1</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>27</AgentPersonMapID>
<Agent>8</Agent>
<Person>17</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>28</AgentPersonMapID>
<Agent>8</Agent>
<Person>18</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>29</AgentPersonMapID>
<Agent>8</Agent>
<Person>19</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>30</AgentPersonMapID>
<Agent>9</Agent>
<Person>20</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>31</AgentPersonMapID>
<Agent>10</Agent>
<Person>21</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>32</AgentPersonMapID>
<Agent>13</Agent>
<Person>24</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>33</AgentPersonMapID>
<Agent>13</Agent>
<Person>25</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>34</AgentPersonMapID>
<Agent>14</Agent>
<Person>5</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>35</AgentPersonMapID>
<Agent>14</Agent>
<Person>26</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>36</AgentPersonMapID>
<Agent>14</Agent>
<Person>12</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>37</AgentPersonMapID>
<Agent>14</Agent>
<Person>10</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>38</AgentPersonMapID>
<Agent>14</Agent>
<Person>1</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>39</AgentPersonMapID>
<Agent>15</Agent>
<Person>29</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>40</AgentPersonMapID>
<Agent>15</Agent>
<Person>30</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>41</AgentPersonMapID>
<Agent>15</Agent>
<Person>31</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>42</AgentPersonMapID>
<Agent>15</Agent>
<Person>32</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>43</AgentPersonMapID>
<Agent>15</Agent>
<Person>1</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>44</AgentPersonMapID>
<Agent>15</Agent>
<Person>33</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>45</AgentPersonMapID>
<Agent>16</Agent>
<Person>29</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>46</AgentPersonMapID>
<Agent>16</Agent>
<Person>30</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>47</AgentPersonMapID>
<Agent>16</Agent>
<Person>31</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>48</AgentPersonMapID>
<Agent>16</Agent>
<Person>32</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>49</AgentPersonMapID>
<Agent>16</Agent>
<Person>1</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>50</AgentPersonMapID>
<Agent>16</Agent>
<Person>33</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>51</AgentPersonMapID>
<Agent>16</Agent>
<Person>15</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>52</AgentPersonMapID>
<Agent>17</Agent>
<Person>29</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>53</AgentPersonMapID>
<Agent>17</Agent>
<Person>30</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>54</AgentPersonMapID>
<Agent>17</Agent>
<Person>31</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>55</AgentPersonMapID>
<Agent>17</Agent>
<Person>32</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>56</AgentPersonMapID>
<Agent>17</Agent>
<Person>1</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>57</AgentPersonMapID>
<Agent>17</Agent>
<Person>33</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>58</AgentPersonMapID>
<Agent>17</Agent>
<Person>15</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>59</AgentPersonMapID>
<Agent>17</Agent>
<Person>1</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>60</AgentPersonMapID>
<Agent>12</Agent>
<Person>22</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>61</AgentPersonMapID>
<Agent>12</Agent>
<Person>23</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>62</AgentPersonMapID>
<Agent>18</Agent>
<Person>9</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>63</AgentPersonMapID>
<Agent>18</Agent>
<Person>37</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>64</AgentPersonMapID>
<Agent>18</Agent>
<Person>38</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>65</AgentPersonMapID>
<Agent>18</Agent>
<Person>39</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>66</AgentPersonMapID>
<Agent>18</Agent>
<Person>1</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>67</AgentPersonMapID>
<Agent>19</Agent>
<Person>17</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>68</AgentPersonMapID>
<Agent>19</Agent>
<Person>18</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>69</AgentPersonMapID>
<Agent>19</Agent>
<Person>1</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>70</AgentPersonMapID>
<Agent>15</Agent>
<Person>41</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>71</AgentPersonMapID>
<Agent>15</Agent>
<Person>40</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>72</AgentPersonMapID>
<Agent>20</Agent>
<Person>42</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
<AgentPersonMapID>73</AgentPersonMapID>
<Agent>20</Agent>
<Person>43</Person>
</_x0038_2_AgentPersonMap>
<_x0038_2_AgentPersonMap>
