=== tetherless-world/POEM/rcads/data/xml/90_Languages.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="_x0039_0_Languages" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="_x0039_0_Languages">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="ISO 3166 Country Code" index-key="ISO_x0020_3166_x0020_Country_x0020_Code " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="LangaugeID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAABqYTCfkURZSY48cDc8kVA3AAAAAABzt7cQZOZAAAAAAAAAAAA5ADAA
XwBMAGEAbgBnAHUAYQBnAGUAcwAAAAAAAACrMY2PjWV6Tp3M5t6QklJQBwAAAGph
MJ+RRFlJjjxwNzyRUDdMAGEAbgBnAGEAdQBnAGUASQBEAAAAAAAAAHO1cvlc2OxA
vFlWCyVKOUUHAAAAamEwn5FEWUmOPHA3PJFQN0wAYQBuAGcAdQBhAGcAZQAAAAAA
AADXCnfAgksWQ6X/pRs+Kvq6BwAAAGphMJ+RRFlJjjxwNzyRUDdJAFMATwA2ADMA
OQAtADEAAAAAAAAA5UTnHY5VTUmWNjfPF5SxGgcAAABqYTCfkURZSY48cDc8kVA3
SQBTAE8ANgAzADkALQAyAAAAAAAAAO86cvUMCMJAphLYr/j5bnEHAAAAamEwn5FE
WUmOPHA3PJFQN1IARgBDAC0ANAA2ADQANgAgAFMAYwByAGkAcAB0ACAAVABhAGcA
AAAAAAAA0xn9MpE9xUqZ4XwkO3WDPQcAAABqYTCfkURZSY48cDc8kVA3SQBTAE8A
IAAzADEANgA2ACAAQwBvAHUAbgB0AHIAeQAgAEMAbwBkAGUAAAAAAAAAubjMRCYr
UEKW7vMgE9z68gcAAABqYTCfkURZSY48cDc8kVA3TABhAG4AZwB1AGEAZwBlAGkA
bgBMAGEAbgBnAHUAYQBnAGUAAAAAAAAABvahd99yrUmnMSdNucn+PQcAAABqYTCf
kURZSY48cDc8kVA3TABhAG4AZwB1AGEAZwBlAGkAbgBMAGEAbgBnAHUAYQBnAGUA
IAAoAEwAYQB0AGkAbgAgAGwAZQB0AHQAZQByAHMAKQAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAADAAAAAUAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="GUID" type="9" value="amEwn5FEWUmOPHA3PJFQNw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="LangaugeID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="qzGNj41lek6dzObekJJSUA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Language" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2130"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="c7Vy+VzY7EC8WVYLJUo5RQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="ISO639-1" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="1wp3wIJLFkOl/6UbPir6ug==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="ISO639-2" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="ISO 639-2 is the alpha-3 code in Codes for the representation of names of languages-- Part 2"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="5UTnHY5VTUmWNjfPF5SxGg==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="RFC-4646_x0020_Script_x0020_Tag" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2190"/>
<od:fieldProperty name="ColumnOrder" type="3" value="5"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="Only use if distinction is needed"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="7zpy9QwIwkCmEtiv+PlucQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="ISO_x0020_3166_x0020_Country_x0020_Code" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2505"/>
<od:fieldProperty name="ColumnOrder" type="3" value="6"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="Only use if distinction is needed (must represent the origin of the instrument, and does not explicitly define region of intended use)"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="0xn9MpE9xUqZ4XwkO3WDPQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="LanguageinLanguage" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2460"/>
<od:fieldProperty name="ColumnOrder" type="3" value="7"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="ubjMRCYrUEKW7vMgE9z68g==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="Bvahd99yrUmnMSdNucn+PQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="3150"/>
<od:fieldProperty name="ColumnOrder" type="3" value="8"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== tetherless-world/POEM/rcads/data/xml/90_Languages.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="90_Languages.xsd" generated="2026-02-26T10:32:03">
<_x0039_0_Languages>
<LanguageID>1</LanguageID>
<Language>English</Language>
<ISO639-1>EN</ISO639-1>
<ISO639-2>ENG</ISO639-2>
<ISO_x0020_3166_x0020_Country_x0020_Code>US</ISO_x0020_3166_x0020_Country_x0020_Code>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>English</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>2</LanguageID>
<Language>Arabic</Language>
<ISO639-1>AR</ISO639-1>
<ISO639-2>ARA</ISO639-2>
<LanguageinLanguage>	اَلْعَرَبِيَّةُ</LanguageinLanguage>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>al-ʿarabiyyah</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>3</LanguageID>
<Language>Chinese (Simplified)</Language>
<ISO639-1>ZH</ISO639-1>
<ISO639-2>CHI</ISO639-2>
<RFC-4646_x0020_Script_x0020_Tag>HANS</RFC-4646_x0020_Script_x0020_Tag>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>4</LanguageID>
<Language>Danish</Language>
<ISO639-1>DA</ISO639-1>
<ISO639-2>DAN</ISO639-2>
<ISO_x0020_3166_x0020_Country_x0020_Code>DK</ISO_x0020_3166_x0020_Country_x0020_Code>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Dansk</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>5</LanguageID>
<Language>Dutch</Language>
<ISO639-1>NL</ISO639-1>
<ISO639-2>DUT</ISO639-2>
<ISO_x0020_3166_x0020_Country_x0020_Code>NL</ISO_x0020_3166_x0020_Country_x0020_Code>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Nederlands</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>6</LanguageID>
<Language>Estonian</Language>
<ISO639-1>ET</ISO639-1>
<ISO639-2>EST</ISO639-2>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Eesti keel</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>7</LanguageID>
<Language>Finnish</Language>
<ISO639-1>FI</ISO639-1>
<ISO639-2>FIN</ISO639-2>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Suomi</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>8</LanguageID>
<Language>French</Language>
<ISO639-1>FR</ISO639-1>
<ISO639-2>FRE</ISO639-2>
<ISO_x0020_3166_x0020_Country_x0020_Code>FR</ISO_x0020_3166_x0020_Country_x0020_Code>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Français</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>9</LanguageID>
<Language>German</Language>
<ISO639-1>DE</ISO639-1>
<ISO639-2>GER</ISO639-2>
<ISO_x0020_3166_x0020_Country_x0020_Code>DE</ISO_x0020_3166_x0020_Country_x0020_Code>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Deutsch</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>10</LanguageID>
<Language>Greek</Language>
<ISO639-1>EL</ISO639-1>
<ISO639-2>GRE</ISO639-2>
<LanguageinLanguage>Νέα Ελληνικά</LanguageinLanguage>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Néa Ellêniká</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>11</LanguageID>
<Language>Hungarian</Language>
<ISO639-1>HU</ISO639-1>
<ISO639-2>HUN</ISO639-2>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Magyar nyelv</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>12</LanguageID>
<Language>Icelandic</Language>
<ISO639-1>IS</ISO639-1>
<ISO639-2>ICE</ISO639-2>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Íslenska</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>13</LanguageID>
<Language>Japanese</Language>
<ISO639-1>JA</ISO639-1>
<ISO639-2>JPN</ISO639-2>
<ISO_x0020_3166_x0020_Country_x0020_Code>JP</ISO_x0020_3166_x0020_Country_x0020_Code>
<LanguageinLanguage>日本語</LanguageinLanguage>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Nihongo</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>14</LanguageID>
<Language>Korean</Language>
<ISO639-1>KO</ISO639-1>
<ISO639-2>KOR</ISO639-2>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>15</LanguageID>
<Language>Lithuanian</Language>
<ISO639-1>LT</ISO639-1>
<ISO639-2>LIT</ISO639-2>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Lietuvių</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>16</LanguageID>
<Language>Norwegian</Language>
<ISO639-1>NO</ISO639-1>
<ISO639-2>NOR</ISO639-2>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Norsk</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>17</LanguageID>
<Language>Persian</Language>
<ISO639-1>FA</ISO639-1>
<ISO639-2>PER</ISO639-2>
<LanguageinLanguage>فارسی</LanguageinLanguage>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Fārsiy</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>18</LanguageID>
<Language>Polish</Language>
<ISO639-1>PL</ISO639-1>
<ISO639-2>POL</ISO639-2>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Polski</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>19</LanguageID>
<Language>Portuguese</Language>
<ISO639-1>PT</ISO639-1>
<ISO639-2>POR</ISO639-2>
<ISO_x0020_3166_x0020_Country_x0020_Code>BR</ISO_x0020_3166_x0020_Country_x0020_Code>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Português</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>20</LanguageID>
<Language>Slovenian</Language>
<ISO639-1>SL</ISO639-1>
<ISO639-2>SLV</ISO639-2>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Slovenščina</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>21</LanguageID>
<Language>Spanish</Language>
<ISO639-1>ES</ISO639-1>
<ISO639-2>SPA</ISO639-2>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Español</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>22</LanguageID>
<Language>Swedish</Language>
<ISO639-1>SV</ISO639-1>
<ISO639-2>SWE</ISO639-2>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Svenska</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>23</LanguageID>
<Language>Turkish</Language>
<ISO639-1>TR</ISO639-1>
<ISO639-2>TUR</ISO639-2>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Türkçe</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>24</LanguageID>
<Language>Urdu</Language>
<ISO639-1>UR</ISO639-1>
<ISO639-2>URD</ISO639-2>
<LanguageinLanguage>اُردُو</LanguageinLanguage>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Urduw</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>25</LanguageID>
<Language>Chinese (Traditional)</Language>
<ISO639-1>ZH</ISO639-1>
<ISO639-2>CHI</ISO639-2>
<RFC-4646_x0020_Script_x0020_Tag>HANT</RFC-4646_x0020_Script_x0020_Tag>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>26</LanguageID>
<Language>Swahili</Language>
<ISO639-1>SW</ISO639-1>
<ISO639-2>SWA</ISO639-2>
<LanguageinLanguage>كِسوَحِيلِ</LanguageinLanguage>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Kiswahili</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>27</LanguageID>
<Language>Serbian</Language>
<ISO639-1>SR</ISO639-1>
<ISO639-2>SRP</ISO639-2>
<LanguageinLanguage>Српски</LanguageinLanguage>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Srpski</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>28</LanguageID>
<Language>Malay</Language>
<ISO639-1>MS</ISO639-1>
<ISO639-2>MSA</ISO639-2>
<LanguageinLanguage>بهاس ملايو</LanguageinLanguage>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>bahasa Melayu</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>29</LanguageID>
<Language>Bengali</Language>
<ISO639-1>BN</ISO639-1>
<ISO639-2>BEN</ISO639-2>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>30</LanguageID>
<Language>French</Language>
<ISO639-1>FR</ISO639-1>
<ISO639-2>FRE</ISO639-2>
<ISO_x0020_3166_x0020_Country_x0020_Code>CA</ISO_x0020_3166_x0020_Country_x0020_Code>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Français</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>31</LanguageID>
<Language>Hindi</Language>
<ISO639-1>HI</ISO639-1>
<ISO639-2>HIN</ISO639-2>
<LanguageinLanguage>हिन्दी</LanguageinLanguage>
<LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>Hindī</LanguageinLanguage_x0020__x0028_Latin_x0020_letters_x0029_>
</_x0039_0_Languages>
<_x0039_0_Languages>
<LanguageID>32</LanguageID>
<Language>Punjabi</Language>
