=== tetherless-world/POEM/rcads/data/xml/91_Informant.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="_x0039_1_Informant" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="_x0039_1_Informant">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="InformantID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="GUID" type="9" value="BYffSRncwkKaQWnCTfb5Fg==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAAFh99JGdzCQppBacJN9vkWAAAAAFU3tXcRYuZAAAAAAAAAAAA5ADEA
XwBJAG4AZgBvAHIAbQBhAG4AdAAAAAAAAADwQ/c7UhhERaWhHqr5bGnWBwAAAAWH
30kZ3MJCmkFpwk32+RZJAG4AZgBvAHIAbQBhAG4AdABJAEQAAAAAAAAAnSpVaSnv
9UqEXob+QcwBRgcAAAAFh99JGdzCQppBacJN9vkWSQBuAGYAbwByAG0AYQBuAHQA
AAAAAAAABLQNh0/qZEyapOVcTt1dMgAAAAAvK7F5EWLmQAAAAAAAAAAAOQAyAF8A
SQBuAGYAbwByAG0AYQBuAHQAVAB5AHAAZQBzAAAAAAAAABP4hD1xT21BrH95Tfj0
NIkHAAAABLQNh0/qZEyapOVcTt1dMkkAbgBmAG8AcgBtAGEAbgB0AFQAeQBwAGUA
SQBEAAAAAAAAAJn2mx7x0fxGua3BzQ4v96IHAAAABLQNh0/qZEyapOVcTt1dMkkA
bgBmAG8AcgBtAGEAbgB0AFQAeQBwAGUAAAAAAAAAMwHVK2H4vUClsMIyKDKANgcA
AAAFh99JGdzCQppBacJN9vkWSQBuAGYAbwByAG0AYQBuAHQAVAB5AHAAZQAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAADAAAAAUAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="InformantID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="8EP3O1IYREWloR6q+Wxp1g==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Informant" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="nSpVaSnv9UqEXob+QcwBRg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="InformantType" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="MwHVK2H4vUClsMIyKDKANg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [92_InformantTypes].[InformantTypeID], [92_InformantTypes].[InformantType] FROM 92_InformantTypes ORDER BY [InformantTypeID]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== tetherless-world/POEM/rcads/data/xml/91_Informant.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="91_Informant.xsd" generated="2025-07-15T15:45:48">
<_x0039_1_Informant>
<InformantID>1</InformantID>
<Informant>Youth</Informant>
<InformantType>1</InformantType>
</_x0039_1_Informant>
<_x0039_1_Informant>
<InformantID>2</InformantID>
<Informant>Caregiver</Informant>
<InformantType>2</InformantType>
</_x0039_1_Informant>
<_x0039_1_Informant>
<InformantID>3</InformantID>
<Informant>Teacher</Informant>
<InformantType>2</InformantType>
</_x0039_1_Informant>
<_x0039_1_Informant>
<InformantID>4</InformantID>
<Informant>Adult</Informant>
<InformantType>1</InformantType>
</_x0039_1_Informant>
<_x0039_1_Informant>
<InformantID>5</InformantID>
<Informant>Therapist</Informant>
<InformantType>2</InformantType>
</_x0039_1_Informant>
</dataroot>
